# character 1 - 3
char: 1

version: "1.3.35"
clientVer: "229126"
authServer: "http://103.70.76.250/login/index.php"
ipPort: "103.70.76.250:5678"
authParams:
  acc: Username
  pwd: Password

#账户
username: "0978263876"
#密码
password: "0978263876"
#交易密码 如果没有不用管
authPass: ""
#accId: 1058764751661694976

HuntConfig:
  # 备战精英释放间隔时间(秒)
  PrepEliteCD: 25
  # 是否带队友一起飞图true(会全队一起飞地图)false(仅自己飞)
  CarryTeam: false
  #输入狩猎的怪物清单(前面加#表示不狩猎)
  Mini:
    - "狸猫"
    - "蓝疯兔"
    - "波利之王"
    - "摇滚蝗虫"
    - "蛙王"
    - "直升机哥布灵"
    - "龙蝇"
    - "流浪之狼"
    - "枯树精"
    - "狮鹫兽"
    - "安毕斯"
    - "妖君"
    - "兽人婴儿"
    - "南瓜先生"
    - "半龙人"
    - "草精"
    - "鹗枭首领"
    - "爱丽丝女仆"
    - "艾斯恩魔女"
    - "弑神者"
    - "迷幻之王"
  #    - "大笨钟"
  #    - "钟塔守护者"
  #    - "魔灵娃娃"
  #    - "炎之小魔女"
  #    - "吹笛人"
  #    - "银月魔女"
  #    - "暗 赛尼亚"
  MVP:
    - "天使波利"
    - "黄金虫"
    - "恶魔波利"
    - "海盗之王"
    - "海神"
    - "哥布灵首领"
    - "蜂后"
    - "蚁后"
    - "皮里恩"
    - "虎王"
    - "俄塞里斯"
    - "月夜猫"
    - "兽人英雄"
    - "犬妖首领"
    - "死灵"
    - "阿特罗斯"
    - "兽人酋长"
    #    - "迪塔勒泰晤勒"
    - "鹗枭男爵"
    - "血腥骑士"
    - "巴风特"
    - "黑暗之王"
  #  - "时间管理人"
  #  - "斯佩夏尔"
  #  - "冰暴骑士"
  #  - "炎之领主卡浩"
  #  - "圣天使波利"
  #  - "凯特莉娜"
  #  - "艾勒梅斯"
  HMVP:
    - "卡仑"
#    - "狼外婆"