// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.4.0
// source: ActHitPolly.proto

package Cmd

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ActHiyPollyParam int32

const (
	ActHiyPollyParam_ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST ActHiyPollyParam = 1
	ActHiyPollyParam_ACTHIYPOLLYPARAM_HIT_POLLY           ActHiyPollyParam = 2
	ActHiyPollyParam_ACTHIYPOLLYPARAM_SYNC_ACT            ActHiyPollyParam = 3
	ActHiyPollyParam_ACTHIYPOLLYPARAM_SUBMIT_QUEST        ActHiyPollyParam = 4
	ActHiyPollyParam_ACTHIYPOLLYPARAM_QUEST_NTF           ActHiyPollyParam = 5
)

// Enum value maps for ActHiyPollyParam.
var (
	ActHiyPollyParam_name = map[int32]string{
		1: "ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST",
		2: "ACTHIYPOLLYPARAM_HIT_POLLY",
		3: "ACTHIYPOLLYPARAM_SYNC_ACT",
		4: "ACTHIYPOLLYPARAM_SUBMIT_QUEST",
		5: "ACTHIYPOLLYPARAM_QUEST_NTF",
	}
	ActHiyPollyParam_value = map[string]int32{
		"ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST": 1,
		"ACTHIYPOLLYPARAM_HIT_POLLY":           2,
		"ACTHIYPOLLYPARAM_SYNC_ACT":            3,
		"ACTHIYPOLLYPARAM_SUBMIT_QUEST":        4,
		"ACTHIYPOLLYPARAM_QUEST_NTF":           5,
	}
)

func (x ActHiyPollyParam) Enum() *ActHiyPollyParam {
	p := new(ActHiyPollyParam)
	*p = x
	return p
}

func (x ActHiyPollyParam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActHiyPollyParam) Descriptor() protoreflect.EnumDescriptor {
	return file_ActHitPolly_proto_enumTypes[0].Descriptor()
}

func (ActHiyPollyParam) Type() protoreflect.EnumType {
	return &file_ActHitPolly_proto_enumTypes[0]
}

func (x ActHiyPollyParam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ActHiyPollyParam) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ActHiyPollyParam(num)
	return nil
}

// Deprecated: Use ActHiyPollyParam.Descriptor instead.
func (ActHiyPollyParam) EnumDescriptor() ([]byte, []int) {
	return file_ActHitPolly_proto_rawDescGZIP(), []int{0}
}

type EActHitPollyQuestStatus int32

const (
	EActHitPollyQuestStatus_EACCHITPOLLY_QUEST_NOT_OPEN   EActHitPollyQuestStatus = 0
	EActHitPollyQuestStatus_EACCHITPOLLY_QUEST_ON         EActHitPollyQuestStatus = 1
	EActHitPollyQuestStatus_EACCHITPOLLY_QUEST_SUBMITABLE EActHitPollyQuestStatus = 2
	EActHitPollyQuestStatus_EACCHITPOLLY_QUEST_FINISH     EActHitPollyQuestStatus = 3
)

// Enum value maps for EActHitPollyQuestStatus.
var (
	EActHitPollyQuestStatus_name = map[int32]string{
		0: "EACCHITPOLLY_QUEST_NOT_OPEN",
		1: "EACCHITPOLLY_QUEST_ON",
		2: "EACCHITPOLLY_QUEST_SUBMITABLE",
		3: "EACCHITPOLLY_QUEST_FINISH",
	}
	EActHitPollyQuestStatus_value = map[string]int32{
		"EACCHITPOLLY_QUEST_NOT_OPEN":   0,
		"EACCHITPOLLY_QUEST_ON":         1,
		"EACCHITPOLLY_QUEST_SUBMITABLE": 2,
		"EACCHITPOLLY_QUEST_FINISH":     3,
	}
)

func (x EActHitPollyQuestStatus) Enum() *EActHitPollyQuestStatus {
	p := new(EActHitPollyQuestStatus)
	*p = x
	return p
}

func (x EActHitPollyQuestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EActHitPollyQuestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ActHitPolly_proto_enumTypes[1].Descriptor()
}

func (EActHitPollyQuestStatus) Type() protoreflect.EnumType {
	return &file_ActHitPolly_proto_enumTypes[1]
}

func (x EActHitPollyQuestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EActHitPollyQuestStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EActHitPollyQuestStatus(num)
	return nil
}

// Deprecated: Use EActHitPollyQuestStatus.Descriptor instead.
func (EActHitPollyQuestStatus) EnumDescriptor() ([]byte, []int) {
	return file_ActHitPolly_proto_rawDescGZIP(), []int{1}
}

type ActivityHitPollyQuestItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questid *uint32                  `protobuf:"varint,1,opt,name=questid" json:"questid,omitempty"`
	Status  *EActHitPollyQuestStatus `protobuf:"varint,2,opt,name=status,enum=Cmd.EActHitPollyQuestStatus,def=0" json:"status,omitempty"`
	Process *uint32                  `protobuf:"varint,3,opt,name=process" json:"process,omitempty"`
}

// Default values for ActivityHitPollyQuestItem fields.
const (
	Default_ActivityHitPollyQuestItem_Status = EActHitPollyQuestStatus_EACCHITPOLLY_QUEST_NOT_OPEN
)

func (x *ActivityHitPollyQuestItem) Reset() {
	*x = ActivityHitPollyQuestItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ActHitPolly_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityHitPollyQuestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityHitPollyQuestItem) ProtoMessage() {}

func (x *ActivityHitPollyQuestItem) ProtoReflect() protoreflect.Message {
	mi := &file_ActHitPolly_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityHitPollyQuestItem.ProtoReflect.Descriptor instead.
func (*ActivityHitPollyQuestItem) Descriptor() ([]byte, []int) {
	return file_ActHitPolly_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityHitPollyQuestItem) GetQuestid() uint32 {
	if x != nil && x.Questid != nil {
		return *x.Questid
	}
	return 0
}

func (x *ActivityHitPollyQuestItem) GetStatus() EActHitPollyQuestStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Default_ActivityHitPollyQuestItem_Status
}

func (x *ActivityHitPollyQuestItem) GetProcess() uint32 {
	if x != nil && x.Process != nil {
		return *x.Process
	}
	return 0
}

type ActityHitedPollyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round    *uint32 `protobuf:"varint,1,opt,name=round" json:"round,omitempty"`
	Pos      *uint32 `protobuf:"varint,2,opt,name=pos" json:"pos,omitempty"`
	Rewardid *uint32 `protobuf:"varint,3,opt,name=rewardid" json:"rewardid,omitempty"`
}

func (x *ActityHitedPollyInfo) Reset() {
	*x = ActityHitedPollyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ActHitPolly_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActityHitedPollyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActityHitedPollyInfo) ProtoMessage() {}

func (x *ActityHitedPollyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ActHitPolly_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActityHitedPollyInfo.ProtoReflect.Descriptor instead.
func (*ActityHitedPollyInfo) Descriptor() ([]byte, []int) {
	return file_ActHitPolly_proto_rawDescGZIP(), []int{1}
}

func (x *ActityHitedPollyInfo) GetRound() uint32 {
	if x != nil && x.Round != nil {
		return *x.Round
	}
	return 0
}

func (x *ActityHitedPollyInfo) GetPos() uint32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *ActityHitedPollyInfo) GetRewardid() uint32 {
	if x != nil && x.Rewardid != nil {
		return *x.Rewardid
	}
	return 0
}

type ActityQueryHitedList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd          *Command                `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=226" json:"cmd,omitempty"`
	Param        *ActHiyPollyParam       `protobuf:"varint,2,opt,name=param,enum=Cmd.ActHiyPollyParam,def=1" json:"param,omitempty"`
	Round        *uint32                 `protobuf:"varint,3,opt,name=round" json:"round,omitempty"`
	Currentround *uint32                 `protobuf:"varint,4,opt,name=currentround" json:"currentround,omitempty"`
	List         []*ActityHitedPollyInfo `protobuf:"bytes,5,rep,name=list" json:"list,omitempty"`
	Restbuy      *uint32                 `protobuf:"varint,6,opt,name=restbuy" json:"restbuy,omitempty"`
}

// Default values for ActityQueryHitedList fields.
const (
	Default_ActityQueryHitedList_Cmd   = Command_ACTHITPOLLY_PROTOCMD
	Default_ActityQueryHitedList_Param = ActHiyPollyParam_ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST
)

func (x *ActityQueryHitedList) Reset() {
	*x = ActityQueryHitedList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ActHitPolly_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActityQueryHitedList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActityQueryHitedList) ProtoMessage() {}

func (x *ActityQueryHitedList) ProtoReflect() protoreflect.Message {
	mi := &file_ActHitPolly_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActityQueryHitedList.ProtoReflect.Descriptor instead.
func (*ActityQueryHitedList) Descriptor() ([]byte, []int) {
	return file_ActHitPolly_proto_rawDescGZIP(), []int{2}
}

func (x *ActityQueryHitedList) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_ActityQueryHitedList_Cmd
}

func (x *ActityQueryHitedList) GetParam() ActHiyPollyParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_ActityQueryHitedList_Param
}

func (x *ActityQueryHitedList) GetRound() uint32 {
	if x != nil && x.Round != nil {
		return *x.Round
	}
	return 0
}

func (x *ActityQueryHitedList) GetCurrentround() uint32 {
	if x != nil && x.Currentround != nil {
		return *x.Currentround
	}
	return 0
}

func (x *ActityQueryHitedList) GetList() []*ActityHitedPollyInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ActityQueryHitedList) GetRestbuy() uint32 {
	if x != nil && x.Restbuy != nil {
		return *x.Restbuy
	}
	return 0
}

type ActivityHitPolly struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd      *Command          `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=226" json:"cmd,omitempty"`
	Param    *ActHiyPollyParam `protobuf:"varint,2,opt,name=param,enum=Cmd.ActHiyPollyParam,def=2" json:"param,omitempty"`
	Round    *uint32           `protobuf:"varint,3,opt,name=round" json:"round,omitempty"`
	Pos      *uint32           `protobuf:"varint,4,opt,name=pos" json:"pos,omitempty"`
	Rewardid *uint32           `protobuf:"varint,5,opt,name=rewardid" json:"rewardid,omitempty"`
}

// Default values for ActivityHitPolly fields.
const (
	Default_ActivityHitPolly_Cmd   = Command_ACTHITPOLLY_PROTOCMD
	Default_ActivityHitPolly_Param = ActHiyPollyParam_ACTHIYPOLLYPARAM_HIT_POLLY
)

func (x *ActivityHitPolly) Reset() {
	*x = ActivityHitPolly{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ActHitPolly_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityHitPolly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityHitPolly) ProtoMessage() {}

func (x *ActivityHitPolly) ProtoReflect() protoreflect.Message {
	mi := &file_ActHitPolly_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityHitPolly.ProtoReflect.Descriptor instead.
func (*ActivityHitPolly) Descriptor() ([]byte, []int) {
	return file_ActHitPolly_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityHitPolly) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_ActivityHitPolly_Cmd
}

func (x *ActivityHitPolly) GetParam() ActHiyPollyParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_ActivityHitPolly_Param
}

func (x *ActivityHitPolly) GetRound() uint32 {
	if x != nil && x.Round != nil {
		return *x.Round
	}
	return 0
}

func (x *ActivityHitPolly) GetPos() uint32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *ActivityHitPolly) GetRewardid() uint32 {
	if x != nil && x.Rewardid != nil {
		return *x.Rewardid
	}
	return 0
}

type ActityHitPollySync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd         *Command                     `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=226" json:"cmd,omitempty"`
	Param       *ActHiyPollyParam            `protobuf:"varint,2,opt,name=param,enum=Cmd.ActHiyPollyParam,def=3" json:"param,omitempty"`
	Globalactid *uint32                      `protobuf:"varint,3,opt,name=globalactid" json:"globalactid,omitempty"`
	Curround    *uint32                      `protobuf:"varint,4,opt,name=curround" json:"curround,omitempty"`
	Quests      []*ActivityHitPollyQuestItem `protobuf:"bytes,5,rep,name=quests" json:"quests,omitempty"`
}

// Default values for ActityHitPollySync fields.
const (
	Default_ActityHitPollySync_Cmd   = Command_ACTHITPOLLY_PROTOCMD
	Default_ActityHitPollySync_Param = ActHiyPollyParam_ACTHIYPOLLYPARAM_SYNC_ACT
)

func (x *ActityHitPollySync) Reset() {
	*x = ActityHitPollySync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ActHitPolly_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActityHitPollySync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActityHitPollySync) ProtoMessage() {}

func (x *ActityHitPollySync) ProtoReflect() protoreflect.Message {
	mi := &file_ActHitPolly_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActityHitPollySync.ProtoReflect.Descriptor instead.
func (*ActityHitPollySync) Descriptor() ([]byte, []int) {
	return file_ActHitPolly_proto_rawDescGZIP(), []int{4}
}

func (x *ActityHitPollySync) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_ActityHitPollySync_Cmd
}

func (x *ActityHitPollySync) GetParam() ActHiyPollyParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_ActityHitPollySync_Param
}

func (x *ActityHitPollySync) GetGlobalactid() uint32 {
	if x != nil && x.Globalactid != nil {
		return *x.Globalactid
	}
	return 0
}

func (x *ActityHitPollySync) GetCurround() uint32 {
	if x != nil && x.Curround != nil {
		return *x.Curround
	}
	return 0
}

func (x *ActityHitPollySync) GetQuests() []*ActivityHitPollyQuestItem {
	if x != nil {
		return x.Quests
	}
	return nil
}

type ActityHitPollySubmitQuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd     *Command          `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=226" json:"cmd,omitempty"`
	Param   *ActHiyPollyParam `protobuf:"varint,2,opt,name=param,enum=Cmd.ActHiyPollyParam,def=4" json:"param,omitempty"`
	Questid *uint32           `protobuf:"varint,3,opt,name=questid" json:"questid,omitempty"`
}

// Default values for ActityHitPollySubmitQuest fields.
const (
	Default_ActityHitPollySubmitQuest_Cmd   = Command_ACTHITPOLLY_PROTOCMD
	Default_ActityHitPollySubmitQuest_Param = ActHiyPollyParam_ACTHIYPOLLYPARAM_SUBMIT_QUEST
)

func (x *ActityHitPollySubmitQuest) Reset() {
	*x = ActityHitPollySubmitQuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ActHitPolly_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActityHitPollySubmitQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActityHitPollySubmitQuest) ProtoMessage() {}

func (x *ActityHitPollySubmitQuest) ProtoReflect() protoreflect.Message {
	mi := &file_ActHitPolly_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActityHitPollySubmitQuest.ProtoReflect.Descriptor instead.
func (*ActityHitPollySubmitQuest) Descriptor() ([]byte, []int) {
	return file_ActHitPolly_proto_rawDescGZIP(), []int{5}
}

func (x *ActityHitPollySubmitQuest) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_ActityHitPollySubmitQuest_Cmd
}

func (x *ActityHitPollySubmitQuest) GetParam() ActHiyPollyParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_ActityHitPollySubmitQuest_Param
}

func (x *ActityHitPollySubmitQuest) GetQuestid() uint32 {
	if x != nil && x.Questid != nil {
		return *x.Questid
	}
	return 0
}

type ActityHitPollyNtfQuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd    *Command                     `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=226" json:"cmd,omitempty"`
	Param  *ActHiyPollyParam            `protobuf:"varint,2,opt,name=param,enum=Cmd.ActHiyPollyParam,def=5" json:"param,omitempty"`
	Quests []*ActivityHitPollyQuestItem `protobuf:"bytes,7,rep,name=quests" json:"quests,omitempty"`
}

// Default values for ActityHitPollyNtfQuest fields.
const (
	Default_ActityHitPollyNtfQuest_Cmd   = Command_ACTHITPOLLY_PROTOCMD
	Default_ActityHitPollyNtfQuest_Param = ActHiyPollyParam_ACTHIYPOLLYPARAM_QUEST_NTF
)

func (x *ActityHitPollyNtfQuest) Reset() {
	*x = ActityHitPollyNtfQuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ActHitPolly_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActityHitPollyNtfQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActityHitPollyNtfQuest) ProtoMessage() {}

func (x *ActityHitPollyNtfQuest) ProtoReflect() protoreflect.Message {
	mi := &file_ActHitPolly_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActityHitPollyNtfQuest.ProtoReflect.Descriptor instead.
func (*ActityHitPollyNtfQuest) Descriptor() ([]byte, []int) {
	return file_ActHitPolly_proto_rawDescGZIP(), []int{6}
}

func (x *ActityHitPollyNtfQuest) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_ActityHitPollyNtfQuest_Cmd
}

func (x *ActityHitPollyNtfQuest) GetParam() ActHiyPollyParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_ActityHitPollyNtfQuest_Param
}

func (x *ActityHitPollyNtfQuest) GetQuests() []*ActivityHitPollyQuestItem {
	if x != nil {
		return x.Quests
	}
	return nil
}

var File_ActHitPolly_proto protoreflect.FileDescriptor

var file_ActHitPolly_proto_rawDesc = []byte{
	0x0a, 0x11, 0x41, 0x63, 0x74, 0x48, 0x69, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x43, 0x6d, 0x64, 0x1a, 0x0a, 0x78, 0x43, 0x6d, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x19, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x48, 0x69, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x51, 0x75, 0x65, 0x73, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x64, 0x12, 0x51, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x43,
	0x6d, 0x64, 0x2e, 0x45, 0x41, 0x63, 0x74, 0x48, 0x69, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x3a, 0x1b, 0x45, 0x41, 0x43, 0x43,
	0x48, 0x49, 0x54, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x5f, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4e,
	0x4f, 0x54, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x22, 0x5a, 0x0a, 0x14, 0x41, 0x63, 0x74,
	0x69, 0x74, 0x79, 0x48, 0x69, 0x74, 0x65, 0x64, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x69, 0x64, 0x22, 0xa2, 0x02, 0x0a, 0x14, 0x41, 0x63, 0x74, 0x69, 0x74, 0x79,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x69, 0x74, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34,
	0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d,
	0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x14, 0x41, 0x43, 0x54, 0x48, 0x49,
	0x54, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52,
	0x03, 0x63, 0x6d, 0x64, 0x12, 0x51, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x48, 0x69, 0x79,
	0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x24, 0x41, 0x43, 0x54, 0x48,
	0x49, 0x59, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x51, 0x55, 0x45,
	0x52, 0x59, 0x5f, 0x48, 0x49, 0x54, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x5f, 0x4c, 0x49, 0x53, 0x54,
	0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x12, 0x2d, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x74, 0x79, 0x48, 0x69, 0x74, 0x65,
	0x64, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x74, 0x62, 0x75, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x72, 0x65, 0x73, 0x74, 0x62, 0x75, 0x79, 0x22, 0xd5, 0x01, 0x0a, 0x10, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x48, 0x69, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x12,
	0x34, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43,
	0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x14, 0x41, 0x43, 0x54, 0x48,
	0x49, 0x54, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44,
	0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x47, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x48, 0x69,
	0x79, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x1a, 0x41, 0x43, 0x54,
	0x48, 0x49, 0x59, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x48, 0x49,
	0x54, 0x5f, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x69, 0x64, 0x22, 0x88, 0x02, 0x0a, 0x12, 0x41, 0x63, 0x74, 0x69, 0x74, 0x79, 0x48, 0x69, 0x74,
	0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x34, 0x0a, 0x03, 0x63, 0x6d, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x14, 0x41, 0x43, 0x54, 0x48, 0x49, 0x54, 0x50, 0x4f, 0x4c, 0x4c,
	0x59, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12,
	0x46, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x48, 0x69, 0x79, 0x50, 0x6f, 0x6c, 0x6c, 0x79,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x19, 0x41, 0x43, 0x54, 0x48, 0x49, 0x59, 0x50, 0x4f, 0x4c,
	0x4c, 0x59, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x5f, 0x41, 0x43, 0x54,
	0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x61, 0x63, 0x74, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x67, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x36, 0x0a, 0x06, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x48, 0x69, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0xb7, 0x01,
	0x0a, 0x19, 0x41, 0x63, 0x74, 0x69, 0x74, 0x79, 0x48, 0x69, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x79,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x03, 0x63,
	0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x14, 0x41, 0x43, 0x54, 0x48, 0x49, 0x54, 0x50, 0x4f,
	0x4c, 0x4c, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d,
	0x64, 0x12, 0x4a, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x48, 0x69, 0x79, 0x50, 0x6f, 0x6c,
	0x6c, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x1d, 0x41, 0x43, 0x54, 0x48, 0x49, 0x59, 0x50,
	0x4f, 0x4c, 0x4c, 0x59, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x53, 0x55, 0x42, 0x4d, 0x49, 0x54,
	0x5f, 0x51, 0x55, 0x45, 0x53, 0x54, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a,
	0x07, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x64, 0x22, 0xcf, 0x01, 0x0a, 0x16, 0x41, 0x63, 0x74, 0x69,
	0x74, 0x79, 0x48, 0x69, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x4e, 0x74, 0x66, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x34, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x14, 0x41,
	0x43, 0x54, 0x48, 0x49, 0x54, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f,
	0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x47, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x41, 0x63,
	0x74, 0x48, 0x69, 0x79, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x1a,
	0x41, 0x43, 0x54, 0x48, 0x49, 0x59, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x50, 0x41, 0x52, 0x41, 0x4d,
	0x5f, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x54, 0x46, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x12, 0x36, 0x0a, 0x06, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x48, 0x69, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x51, 0x75, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x06, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2a, 0xbe, 0x01, 0x0a, 0x10, 0x41, 0x63,
	0x74, 0x48, 0x69, 0x79, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x28,
	0x0a, 0x24, 0x41, 0x43, 0x54, 0x48, 0x49, 0x59, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x50, 0x41, 0x52,
	0x41, 0x4d, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x48, 0x49, 0x54, 0x50, 0x4f, 0x4c, 0x4c,
	0x59, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x41, 0x43, 0x54, 0x48,
	0x49, 0x59, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x48, 0x49, 0x54,
	0x5f, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x43, 0x54, 0x48,
	0x49, 0x59, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x53, 0x59, 0x4e,
	0x43, 0x5f, 0x41, 0x43, 0x54, 0x10, 0x03, 0x12, 0x21, 0x0a, 0x1d, 0x41, 0x43, 0x54, 0x48, 0x49,
	0x59, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x53, 0x55, 0x42, 0x4d,
	0x49, 0x54, 0x5f, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x04, 0x12, 0x1e, 0x0a, 0x1a, 0x41, 0x43,
	0x54, 0x48, 0x49, 0x59, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x51,
	0x55, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x54, 0x46, 0x10, 0x05, 0x2a, 0x97, 0x01, 0x0a, 0x17, 0x45,
	0x41, 0x63, 0x74, 0x48, 0x69, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x79, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x1b, 0x45, 0x41, 0x43, 0x43, 0x48, 0x49,
	0x54, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x5f, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x41, 0x43, 0x43, 0x48,
	0x49, 0x54, 0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x5f, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4f, 0x4e,
	0x10, 0x01, 0x12, 0x21, 0x0a, 0x1d, 0x45, 0x41, 0x43, 0x43, 0x48, 0x49, 0x54, 0x50, 0x4f, 0x4c,
	0x4c, 0x59, 0x5f, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x53, 0x55, 0x42, 0x4d, 0x49, 0x54, 0x41,
	0x42, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x45, 0x41, 0x43, 0x43, 0x48, 0x49, 0x54,
	0x50, 0x4f, 0x4c, 0x4c, 0x59, 0x5f, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x46, 0x49, 0x4e, 0x49,
	0x53, 0x48, 0x10, 0x03,
}

var (
	file_ActHitPolly_proto_rawDescOnce sync.Once
	file_ActHitPolly_proto_rawDescData = file_ActHitPolly_proto_rawDesc
)

func file_ActHitPolly_proto_rawDescGZIP() []byte {
	file_ActHitPolly_proto_rawDescOnce.Do(func() {
		file_ActHitPolly_proto_rawDescData = protoimpl.X.CompressGZIP(file_ActHitPolly_proto_rawDescData)
	})
	return file_ActHitPolly_proto_rawDescData
}

var file_ActHitPolly_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ActHitPolly_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ActHitPolly_proto_goTypes = []interface{}{
	(ActHiyPollyParam)(0),             // 0: Cmd.ActHiyPollyParam
	(EActHitPollyQuestStatus)(0),      // 1: Cmd.EActHitPollyQuestStatus
	(*ActivityHitPollyQuestItem)(nil), // 2: Cmd.ActivityHitPollyQuestItem
	(*ActityHitedPollyInfo)(nil),      // 3: Cmd.ActityHitedPollyInfo
	(*ActityQueryHitedList)(nil),      // 4: Cmd.ActityQueryHitedList
	(*ActivityHitPolly)(nil),          // 5: Cmd.ActivityHitPolly
	(*ActityHitPollySync)(nil),        // 6: Cmd.ActityHitPollySync
	(*ActityHitPollySubmitQuest)(nil), // 7: Cmd.ActityHitPollySubmitQuest
	(*ActityHitPollyNtfQuest)(nil),    // 8: Cmd.ActityHitPollyNtfQuest
	(Command)(0),                      // 9: Cmd.Command
}
var file_ActHitPolly_proto_depIdxs = []int32{
	1,  // 0: Cmd.ActivityHitPollyQuestItem.status:type_name -> Cmd.EActHitPollyQuestStatus
	9,  // 1: Cmd.ActityQueryHitedList.cmd:type_name -> Cmd.Command
	0,  // 2: Cmd.ActityQueryHitedList.param:type_name -> Cmd.ActHiyPollyParam
	3,  // 3: Cmd.ActityQueryHitedList.list:type_name -> Cmd.ActityHitedPollyInfo
	9,  // 4: Cmd.ActivityHitPolly.cmd:type_name -> Cmd.Command
	0,  // 5: Cmd.ActivityHitPolly.param:type_name -> Cmd.ActHiyPollyParam
	9,  // 6: Cmd.ActityHitPollySync.cmd:type_name -> Cmd.Command
	0,  // 7: Cmd.ActityHitPollySync.param:type_name -> Cmd.ActHiyPollyParam
	2,  // 8: Cmd.ActityHitPollySync.quests:type_name -> Cmd.ActivityHitPollyQuestItem
	9,  // 9: Cmd.ActityHitPollySubmitQuest.cmd:type_name -> Cmd.Command
	0,  // 10: Cmd.ActityHitPollySubmitQuest.param:type_name -> Cmd.ActHiyPollyParam
	9,  // 11: Cmd.ActityHitPollyNtfQuest.cmd:type_name -> Cmd.Command
	0,  // 12: Cmd.ActityHitPollyNtfQuest.param:type_name -> Cmd.ActHiyPollyParam
	2,  // 13: Cmd.ActityHitPollyNtfQuest.quests:type_name -> Cmd.ActivityHitPollyQuestItem
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_ActHitPolly_proto_init() }
func file_ActHitPolly_proto_init() {
	if File_ActHitPolly_proto != nil {
		return
	}
	file_xCmd_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ActHitPolly_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityHitPollyQuestItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ActHitPolly_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActityHitedPollyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ActHitPolly_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActityQueryHitedList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ActHitPolly_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityHitPolly); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ActHitPolly_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActityHitPollySync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ActHitPolly_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActityHitPollySubmitQuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ActHitPolly_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActityHitPollyNtfQuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ActHitPolly_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ActHitPolly_proto_goTypes,
		DependencyIndexes: file_ActHitPolly_proto_depIdxs,
		EnumInfos:         file_ActHitPolly_proto_enumTypes,
		MessageInfos:      file_ActHitPolly_proto_msgTypes,
	}.Build()
	File_ActHitPolly_proto = out.File
	file_ActHitPolly_proto_rawDesc = nil
	file_ActHitPolly_proto_goTypes = nil
	file_ActHitPolly_proto_depIdxs = nil
}
