// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: GoalCmd.proto

package Cmd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoalParam int32

const (
	GoalParam_GOALPARAM_QUERY_LIST       GoalParam = 1
	GoalParam_GOALPARAM_UPDATE_ITEM      GoalParam = 2
	GoalParam_GOALPARAM_UPDATE_GROUP     GoalParam = 3
	GoalParam_GOALPARAM_UPDATE_SCORE     GoalParam = 4
	GoalParam_GOALPARAM_GET_GROUP_REWARD GoalParam = 5
	GoalParam_GOALPARAM_GET_ITEM_SCORE   GoalParam = 6
	GoalParam_GOALPARAM_GET_SCORE_REWARD GoalParam = 7
)

// Enum value maps for GoalParam.
var (
	GoalParam_name = map[int32]string{
		1: "GOALPARAM_QUERY_LIST",
		2: "GOALPARAM_UPDATE_ITEM",
		3: "GOALPARAM_UPDATE_GROUP",
		4: "GOALPARAM_UPDATE_SCORE",
		5: "GOALPARAM_GET_GROUP_REWARD",
		6: "GOALPARAM_GET_ITEM_SCORE",
		7: "GOALPARAM_GET_SCORE_REWARD",
	}
	GoalParam_value = map[string]int32{
		"GOALPARAM_QUERY_LIST":       1,
		"GOALPARAM_UPDATE_ITEM":      2,
		"GOALPARAM_UPDATE_GROUP":     3,
		"GOALPARAM_UPDATE_SCORE":     4,
		"GOALPARAM_GET_GROUP_REWARD": 5,
		"GOALPARAM_GET_ITEM_SCORE":   6,
		"GOALPARAM_GET_SCORE_REWARD": 7,
	}
)

func (x GoalParam) Enum() *GoalParam {
	p := new(GoalParam)
	*p = x
	return p
}

func (x GoalParam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoalParam) Descriptor() protoreflect.EnumDescriptor {
	return file_GoalCmd_proto_enumTypes[0].Descriptor()
}

func (GoalParam) Type() protoreflect.EnumType {
	return &file_GoalCmd_proto_enumTypes[0]
}

func (x GoalParam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *GoalParam) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = GoalParam(num)
	return nil
}

// Deprecated: Use GoalParam.Descriptor instead.
func (GoalParam) EnumDescriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{0}
}

type EGoalStatus int32

const (
	EGoalStatus_EGOALSTATUS_MIN    EGoalStatus = 0
	EGoalStatus_EGOALSTATUS_ACTIVE EGoalStatus = 1
	EGoalStatus_EGOALSTATUS_FINISH EGoalStatus = 2
	EGoalStatus_EGOALSTATUS_MAX    EGoalStatus = 3
)

// Enum value maps for EGoalStatus.
var (
	EGoalStatus_name = map[int32]string{
		0: "EGOALSTATUS_MIN",
		1: "EGOALSTATUS_ACTIVE",
		2: "EGOALSTATUS_FINISH",
		3: "EGOALSTATUS_MAX",
	}
	EGoalStatus_value = map[string]int32{
		"EGOALSTATUS_MIN":    0,
		"EGOALSTATUS_ACTIVE": 1,
		"EGOALSTATUS_FINISH": 2,
		"EGOALSTATUS_MAX":    3,
	}
)

func (x EGoalStatus) Enum() *EGoalStatus {
	p := new(EGoalStatus)
	*p = x
	return p
}

func (x EGoalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EGoalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_GoalCmd_proto_enumTypes[1].Descriptor()
}

func (EGoalStatus) Type() protoreflect.EnumType {
	return &file_GoalCmd_proto_enumTypes[1]
}

func (x EGoalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EGoalStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EGoalStatus(num)
	return nil
}

// Deprecated: Use EGoalStatus.Descriptor instead.
func (EGoalStatus) EnumDescriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{1}
}

type GoalScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version *string  `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Score   *uint32  `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	Rewards []uint32 `protobuf:"varint,3,rep,name=rewards" json:"rewards,omitempty"`
}

func (x *GoalScore) Reset() {
	*x = GoalScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GoalCmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoalScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalScore) ProtoMessage() {}

func (x *GoalScore) ProtoReflect() protoreflect.Message {
	mi := &file_GoalCmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalScore.ProtoReflect.Descriptor instead.
func (*GoalScore) Descriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{0}
}

func (x *GoalScore) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *GoalScore) GetScore() uint32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *GoalScore) GetRewards() []uint32 {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type GoalItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *uint32      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Process *uint32      `protobuf:"varint,2,opt,name=process" json:"process,omitempty"`
	Status  *EGoalStatus `protobuf:"varint,3,opt,name=status,enum=Cmd.EGoalStatus" json:"status,omitempty"`
	Point   *bool        `protobuf:"varint,4,opt,name=point" json:"point,omitempty"`
}

func (x *GoalItem) Reset() {
	*x = GoalItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GoalCmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoalItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalItem) ProtoMessage() {}

func (x *GoalItem) ProtoReflect() protoreflect.Message {
	mi := &file_GoalCmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalItem.ProtoReflect.Descriptor instead.
func (*GoalItem) Descriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{1}
}

func (x *GoalItem) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GoalItem) GetProcess() uint32 {
	if x != nil && x.Process != nil {
		return *x.Process
	}
	return 0
}

func (x *GoalItem) GetStatus() EGoalStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return EGoalStatus_EGOALSTATUS_MIN
}

func (x *GoalItem) GetPoint() bool {
	if x != nil && x.Point != nil {
		return *x.Point
	}
	return false
}

type GoalGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group       *uint32 `protobuf:"varint,1,opt,name=group" json:"group,omitempty"`
	Rewardcount *uint32 `protobuf:"varint,2,opt,name=rewardcount" json:"rewardcount,omitempty"`
}

func (x *GoalGroup) Reset() {
	*x = GoalGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GoalCmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoalGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalGroup) ProtoMessage() {}

func (x *GoalGroup) ProtoReflect() protoreflect.Message {
	mi := &file_GoalCmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalGroup.ProtoReflect.Descriptor instead.
func (*GoalGroup) Descriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{2}
}

func (x *GoalGroup) GetGroup() uint32 {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return 0
}

func (x *GoalGroup) GetRewardcount() uint32 {
	if x != nil && x.Rewardcount != nil {
		return *x.Rewardcount
	}
	return 0
}

type QueryGoalListGoalCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd     *Command     `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=75" json:"cmd,omitempty"`
	Param   *GoalParam   `protobuf:"varint,2,opt,name=param,enum=Cmd.GoalParam,def=1" json:"param,omitempty"`
	Version *string      `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Items   []*GoalItem  `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	Groups  []*GoalGroup `protobuf:"bytes,5,rep,name=groups" json:"groups,omitempty"`
	Score   *GoalScore   `protobuf:"bytes,6,opt,name=score" json:"score,omitempty"`
}

// Default values for QueryGoalListGoalCmd fields.
const (
	Default_QueryGoalListGoalCmd_Cmd   = Command_GOAL_PROTOCMD
	Default_QueryGoalListGoalCmd_Param = GoalParam_GOALPARAM_QUERY_LIST
)

func (x *QueryGoalListGoalCmd) Reset() {
	*x = QueryGoalListGoalCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GoalCmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGoalListGoalCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGoalListGoalCmd) ProtoMessage() {}

func (x *QueryGoalListGoalCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GoalCmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGoalListGoalCmd.ProtoReflect.Descriptor instead.
func (*QueryGoalListGoalCmd) Descriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{3}
}

func (x *QueryGoalListGoalCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_QueryGoalListGoalCmd_Cmd
}

func (x *QueryGoalListGoalCmd) GetParam() GoalParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_QueryGoalListGoalCmd_Param
}

func (x *QueryGoalListGoalCmd) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *QueryGoalListGoalCmd) GetItems() []*GoalItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *QueryGoalListGoalCmd) GetGroups() []*GoalGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *QueryGoalListGoalCmd) GetScore() *GoalScore {
	if x != nil {
		return x.Score
	}
	return nil
}

type NewGoalItemUpdateGoalCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command   `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=75" json:"cmd,omitempty"`
	Param *GoalParam `protobuf:"varint,2,opt,name=param,enum=Cmd.GoalParam,def=2" json:"param,omitempty"`
	Item  *GoalItem  `protobuf:"bytes,3,opt,name=item" json:"item,omitempty"`
}

// Default values for NewGoalItemUpdateGoalCmd fields.
const (
	Default_NewGoalItemUpdateGoalCmd_Cmd   = Command_GOAL_PROTOCMD
	Default_NewGoalItemUpdateGoalCmd_Param = GoalParam_GOALPARAM_UPDATE_ITEM
)

func (x *NewGoalItemUpdateGoalCmd) Reset() {
	*x = NewGoalItemUpdateGoalCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GoalCmd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGoalItemUpdateGoalCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGoalItemUpdateGoalCmd) ProtoMessage() {}

func (x *NewGoalItemUpdateGoalCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GoalCmd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGoalItemUpdateGoalCmd.ProtoReflect.Descriptor instead.
func (*NewGoalItemUpdateGoalCmd) Descriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{4}
}

func (x *NewGoalItemUpdateGoalCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_NewGoalItemUpdateGoalCmd_Cmd
}

func (x *NewGoalItemUpdateGoalCmd) GetParam() GoalParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_NewGoalItemUpdateGoalCmd_Param
}

func (x *NewGoalItemUpdateGoalCmd) GetItem() *GoalItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type NewGroupUpdateGoalCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command   `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=75" json:"cmd,omitempty"`
	Param *GoalParam `protobuf:"varint,2,opt,name=param,enum=Cmd.GoalParam,def=3" json:"param,omitempty"`
	Group *GoalGroup `protobuf:"bytes,3,opt,name=group" json:"group,omitempty"`
}

// Default values for NewGroupUpdateGoalCmd fields.
const (
	Default_NewGroupUpdateGoalCmd_Cmd   = Command_GOAL_PROTOCMD
	Default_NewGroupUpdateGoalCmd_Param = GoalParam_GOALPARAM_UPDATE_GROUP
)

func (x *NewGroupUpdateGoalCmd) Reset() {
	*x = NewGroupUpdateGoalCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GoalCmd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGroupUpdateGoalCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGroupUpdateGoalCmd) ProtoMessage() {}

func (x *NewGroupUpdateGoalCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GoalCmd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGroupUpdateGoalCmd.ProtoReflect.Descriptor instead.
func (*NewGroupUpdateGoalCmd) Descriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{5}
}

func (x *NewGroupUpdateGoalCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_NewGroupUpdateGoalCmd_Cmd
}

func (x *NewGroupUpdateGoalCmd) GetParam() GoalParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_NewGroupUpdateGoalCmd_Param
}

func (x *NewGroupUpdateGoalCmd) GetGroup() *GoalGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type NewGoalScoreUpdateGoalCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command   `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=75" json:"cmd,omitempty"`
	Param *GoalParam `protobuf:"varint,2,opt,name=param,enum=Cmd.GoalParam,def=4" json:"param,omitempty"`
	Score *GoalScore `protobuf:"bytes,3,opt,name=score" json:"score,omitempty"`
}

// Default values for NewGoalScoreUpdateGoalCmd fields.
const (
	Default_NewGoalScoreUpdateGoalCmd_Cmd   = Command_GOAL_PROTOCMD
	Default_NewGoalScoreUpdateGoalCmd_Param = GoalParam_GOALPARAM_UPDATE_SCORE
)

func (x *NewGoalScoreUpdateGoalCmd) Reset() {
	*x = NewGoalScoreUpdateGoalCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GoalCmd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGoalScoreUpdateGoalCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGoalScoreUpdateGoalCmd) ProtoMessage() {}

func (x *NewGoalScoreUpdateGoalCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GoalCmd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGoalScoreUpdateGoalCmd.ProtoReflect.Descriptor instead.
func (*NewGoalScoreUpdateGoalCmd) Descriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{6}
}

func (x *NewGoalScoreUpdateGoalCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_NewGoalScoreUpdateGoalCmd_Cmd
}

func (x *NewGoalScoreUpdateGoalCmd) GetParam() GoalParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_NewGoalScoreUpdateGoalCmd_Param
}

func (x *NewGoalScoreUpdateGoalCmd) GetScore() *GoalScore {
	if x != nil {
		return x.Score
	}
	return nil
}

type GetGroupRewardGoalCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command   `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=75" json:"cmd,omitempty"`
	Param *GoalParam `protobuf:"varint,2,opt,name=param,enum=Cmd.GoalParam,def=5" json:"param,omitempty"`
	Group *uint32    `protobuf:"varint,3,opt,name=group" json:"group,omitempty"`
}

// Default values for GetGroupRewardGoalCmd fields.
const (
	Default_GetGroupRewardGoalCmd_Cmd   = Command_GOAL_PROTOCMD
	Default_GetGroupRewardGoalCmd_Param = GoalParam_GOALPARAM_GET_GROUP_REWARD
)

func (x *GetGroupRewardGoalCmd) Reset() {
	*x = GetGroupRewardGoalCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GoalCmd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupRewardGoalCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRewardGoalCmd) ProtoMessage() {}

func (x *GetGroupRewardGoalCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GoalCmd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRewardGoalCmd.ProtoReflect.Descriptor instead.
func (*GetGroupRewardGoalCmd) Descriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{7}
}

func (x *GetGroupRewardGoalCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_GetGroupRewardGoalCmd_Cmd
}

func (x *GetGroupRewardGoalCmd) GetParam() GoalParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_GetGroupRewardGoalCmd_Param
}

func (x *GetGroupRewardGoalCmd) GetGroup() uint32 {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return 0
}

type GetScoreGoalCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command   `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=75" json:"cmd,omitempty"`
	Param *GoalParam `protobuf:"varint,2,opt,name=param,enum=Cmd.GoalParam,def=6" json:"param,omitempty"`
	Id    *uint32    `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
}

// Default values for GetScoreGoalCmd fields.
const (
	Default_GetScoreGoalCmd_Cmd   = Command_GOAL_PROTOCMD
	Default_GetScoreGoalCmd_Param = GoalParam_GOALPARAM_GET_ITEM_SCORE
)

func (x *GetScoreGoalCmd) Reset() {
	*x = GetScoreGoalCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GoalCmd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoreGoalCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreGoalCmd) ProtoMessage() {}

func (x *GetScoreGoalCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GoalCmd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreGoalCmd.ProtoReflect.Descriptor instead.
func (*GetScoreGoalCmd) Descriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{8}
}

func (x *GetScoreGoalCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_GetScoreGoalCmd_Cmd
}

func (x *GetScoreGoalCmd) GetParam() GoalParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_GetScoreGoalCmd_Param
}

func (x *GetScoreGoalCmd) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type GetScoreRewardGoalCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd     *Command   `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=75" json:"cmd,omitempty"`
	Param   *GoalParam `protobuf:"varint,2,opt,name=param,enum=Cmd.GoalParam,def=7" json:"param,omitempty"`
	Version *string    `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Value   *uint32    `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
}

// Default values for GetScoreRewardGoalCmd fields.
const (
	Default_GetScoreRewardGoalCmd_Cmd   = Command_GOAL_PROTOCMD
	Default_GetScoreRewardGoalCmd_Param = GoalParam_GOALPARAM_GET_SCORE_REWARD
)

func (x *GetScoreRewardGoalCmd) Reset() {
	*x = GetScoreRewardGoalCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GoalCmd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoreRewardGoalCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreRewardGoalCmd) ProtoMessage() {}

func (x *GetScoreRewardGoalCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GoalCmd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreRewardGoalCmd.ProtoReflect.Descriptor instead.
func (*GetScoreRewardGoalCmd) Descriptor() ([]byte, []int) {
	return file_GoalCmd_proto_rawDescGZIP(), []int{9}
}

func (x *GetScoreRewardGoalCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_GetScoreRewardGoalCmd_Cmd
}

func (x *GetScoreRewardGoalCmd) GetParam() GoalParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_GetScoreRewardGoalCmd_Param
}

func (x *GetScoreRewardGoalCmd) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *GetScoreRewardGoalCmd) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

var File_GoalCmd_proto protoreflect.FileDescriptor

var file_GoalCmd_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x47, 0x6f, 0x61, 0x6c, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x43, 0x6d, 0x64, 0x1a, 0x0a, 0x78, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x55, 0x0a, 0x09, 0x47, 0x6f, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x22, 0x74, 0x0a, 0x08, 0x47, 0x6f, 0x61, 0x6c, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x28, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x43, 0x6d, 0x64, 0x2e, 0x45, 0x47, 0x6f, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x43, 0x0a,
	0x09, 0x47, 0x6f, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x8e, 0x02, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x6f, 0x61, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x43, 0x6d, 0x64, 0x12, 0x2d, 0x0a, 0x03, 0x63,
	0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0d, 0x47, 0x4f, 0x41, 0x4c, 0x5f, 0x50, 0x52, 0x4f,
	0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x3a, 0x0a, 0x05, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x43, 0x6d, 0x64, 0x2e,
	0x47, 0x6f, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x14, 0x47, 0x4f, 0x41, 0x4c, 0x50,
	0x41, 0x52, 0x41, 0x4d, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x52,
	0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x23, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x47, 0x6f, 0x61, 0x6c,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x24, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43,
	0x6d, 0x64, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0xa9, 0x01, 0x0a, 0x18, 0x4e, 0x65, 0x77, 0x47, 0x6f, 0x61, 0x6c, 0x49,
	0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x43, 0x6d, 0x64,
	0x12, 0x2d, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0d, 0x47, 0x4f, 0x41,
	0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12,
	0x3b, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e,
	0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x15,
	0x47, 0x4f, 0x41, 0x4c, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45,
	0x5f, 0x49, 0x54, 0x45, 0x4d, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x21, 0x0a, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6d, 0x64,
	0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22,
	0xaa, 0x01, 0x0a, 0x15, 0x4e, 0x65, 0x77, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x43, 0x6d, 0x64, 0x12, 0x2d, 0x0a, 0x03, 0x63, 0x6d, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0d, 0x47, 0x4f, 0x41, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f,
	0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x3c, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x47, 0x6f,
	0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x16, 0x47, 0x4f, 0x41, 0x4c, 0x50, 0x41, 0x52,
	0x41, 0x4d, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x52,
	0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x24, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x47, 0x6f, 0x61, 0x6c,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0xae, 0x01, 0x0a,
	0x19, 0x4e, 0x65, 0x77, 0x47, 0x6f, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x43, 0x6d, 0x64, 0x12, 0x2d, 0x0a, 0x03, 0x63, 0x6d,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0d, 0x47, 0x4f, 0x41, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x54,
	0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x3c, 0x0a, 0x05, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x47,
	0x6f, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x16, 0x47, 0x4f, 0x41, 0x4c, 0x50, 0x41,
	0x52, 0x41, 0x4d, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x43, 0x4f, 0x52, 0x45,
	0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x47, 0x6f, 0x61,
	0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x9e, 0x01,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x47, 0x6f, 0x61, 0x6c, 0x43, 0x6d, 0x64, 0x12, 0x2d, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x3a, 0x0d, 0x47, 0x4f, 0x41, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d,
	0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x40, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x47, 0x6f, 0x61, 0x6c,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x1a, 0x47, 0x4f, 0x41, 0x4c, 0x50, 0x41, 0x52, 0x41, 0x4d,
	0x5f, 0x47, 0x45, 0x54, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x52, 0x45, 0x57, 0x41, 0x52,
	0x44, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x90,
	0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x43,
	0x6d, 0x64, 0x12, 0x2d, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0d, 0x47,
	0x4f, 0x41, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d,
	0x64, 0x12, 0x3e, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x3a, 0x18, 0x47, 0x4f, 0x41, 0x4c, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x47, 0x45, 0x54, 0x5f,
	0x49, 0x54, 0x45, 0x4d, 0x5f, 0x53, 0x43, 0x4f, 0x52, 0x45, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x22, 0xb8, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x47, 0x6f, 0x61, 0x6c, 0x43, 0x6d, 0x64, 0x12, 0x2d, 0x0a, 0x03, 0x63,
	0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0d, 0x47, 0x4f, 0x41, 0x4c, 0x5f, 0x50, 0x52, 0x4f,
	0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x40, 0x0a, 0x05, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x43, 0x6d, 0x64, 0x2e,
	0x47, 0x6f, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x1a, 0x47, 0x4f, 0x41, 0x4c, 0x50,
	0x41, 0x52, 0x41, 0x4d, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x53, 0x43, 0x4f, 0x52, 0x45, 0x5f, 0x52,
	0x45, 0x57, 0x41, 0x52, 0x44, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0xd6, 0x01, 0x0a,
	0x09, 0x47, 0x6f, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x14, 0x47, 0x4f,
	0x41, 0x4c, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x4c, 0x49,
	0x53, 0x54, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x47, 0x4f, 0x41, 0x4c, 0x50, 0x41, 0x52, 0x41,
	0x4d, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x10, 0x02, 0x12,
	0x1a, 0x0a, 0x16, 0x47, 0x4f, 0x41, 0x4c, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x55, 0x50, 0x44,
	0x41, 0x54, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x03, 0x12, 0x1a, 0x0a, 0x16, 0x47,
	0x4f, 0x41, 0x4c, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f,
	0x53, 0x43, 0x4f, 0x52, 0x45, 0x10, 0x04, 0x12, 0x1e, 0x0a, 0x1a, 0x47, 0x4f, 0x41, 0x4c, 0x50,
	0x41, 0x52, 0x41, 0x4d, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x52,
	0x45, 0x57, 0x41, 0x52, 0x44, 0x10, 0x05, 0x12, 0x1c, 0x0a, 0x18, 0x47, 0x4f, 0x41, 0x4c, 0x50,
	0x41, 0x52, 0x41, 0x4d, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x53, 0x43,
	0x4f, 0x52, 0x45, 0x10, 0x06, 0x12, 0x1e, 0x0a, 0x1a, 0x47, 0x4f, 0x41, 0x4c, 0x50, 0x41, 0x52,
	0x41, 0x4d, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x53, 0x43, 0x4f, 0x52, 0x45, 0x5f, 0x52, 0x45, 0x57,
	0x41, 0x52, 0x44, 0x10, 0x07, 0x2a, 0x67, 0x0a, 0x0b, 0x45, 0x47, 0x6f, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x47, 0x4f, 0x41, 0x4c, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x4d, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x47, 0x4f,
	0x41, 0x4c, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10,
	0x01, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x47, 0x4f, 0x41, 0x4c, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x47, 0x4f,
	0x41, 0x4c, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4d, 0x41, 0x58, 0x10, 0x03,
}

var (
	file_GoalCmd_proto_rawDescOnce sync.Once
	file_GoalCmd_proto_rawDescData = file_GoalCmd_proto_rawDesc
)

func file_GoalCmd_proto_rawDescGZIP() []byte {
	file_GoalCmd_proto_rawDescOnce.Do(func() {
		file_GoalCmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_GoalCmd_proto_rawDescData)
	})
	return file_GoalCmd_proto_rawDescData
}

var file_GoalCmd_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_GoalCmd_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_GoalCmd_proto_goTypes = []interface{}{
	(GoalParam)(0),                    // 0: Cmd.GoalParam
	(EGoalStatus)(0),                  // 1: Cmd.EGoalStatus
	(*GoalScore)(nil),                 // 2: Cmd.GoalScore
	(*GoalItem)(nil),                  // 3: Cmd.GoalItem
	(*GoalGroup)(nil),                 // 4: Cmd.GoalGroup
	(*QueryGoalListGoalCmd)(nil),      // 5: Cmd.QueryGoalListGoalCmd
	(*NewGoalItemUpdateGoalCmd)(nil),  // 6: Cmd.NewGoalItemUpdateGoalCmd
	(*NewGroupUpdateGoalCmd)(nil),     // 7: Cmd.NewGroupUpdateGoalCmd
	(*NewGoalScoreUpdateGoalCmd)(nil), // 8: Cmd.NewGoalScoreUpdateGoalCmd
	(*GetGroupRewardGoalCmd)(nil),     // 9: Cmd.GetGroupRewardGoalCmd
	(*GetScoreGoalCmd)(nil),           // 10: Cmd.GetScoreGoalCmd
	(*GetScoreRewardGoalCmd)(nil),     // 11: Cmd.GetScoreRewardGoalCmd
	(Command)(0),                      // 12: Cmd.Command
}
var file_GoalCmd_proto_depIdxs = []int32{
	1,  // 0: Cmd.GoalItem.status:type_name -> Cmd.EGoalStatus
	12, // 1: Cmd.QueryGoalListGoalCmd.cmd:type_name -> Cmd.Command
	0,  // 2: Cmd.QueryGoalListGoalCmd.param:type_name -> Cmd.GoalParam
	3,  // 3: Cmd.QueryGoalListGoalCmd.items:type_name -> Cmd.GoalItem
	4,  // 4: Cmd.QueryGoalListGoalCmd.groups:type_name -> Cmd.GoalGroup
	2,  // 5: Cmd.QueryGoalListGoalCmd.score:type_name -> Cmd.GoalScore
	12, // 6: Cmd.NewGoalItemUpdateGoalCmd.cmd:type_name -> Cmd.Command
	0,  // 7: Cmd.NewGoalItemUpdateGoalCmd.param:type_name -> Cmd.GoalParam
	3,  // 8: Cmd.NewGoalItemUpdateGoalCmd.item:type_name -> Cmd.GoalItem
	12, // 9: Cmd.NewGroupUpdateGoalCmd.cmd:type_name -> Cmd.Command
	0,  // 10: Cmd.NewGroupUpdateGoalCmd.param:type_name -> Cmd.GoalParam
	4,  // 11: Cmd.NewGroupUpdateGoalCmd.group:type_name -> Cmd.GoalGroup
	12, // 12: Cmd.NewGoalScoreUpdateGoalCmd.cmd:type_name -> Cmd.Command
	0,  // 13: Cmd.NewGoalScoreUpdateGoalCmd.param:type_name -> Cmd.GoalParam
	2,  // 14: Cmd.NewGoalScoreUpdateGoalCmd.score:type_name -> Cmd.GoalScore
	12, // 15: Cmd.GetGroupRewardGoalCmd.cmd:type_name -> Cmd.Command
	0,  // 16: Cmd.GetGroupRewardGoalCmd.param:type_name -> Cmd.GoalParam
	12, // 17: Cmd.GetScoreGoalCmd.cmd:type_name -> Cmd.Command
	0,  // 18: Cmd.GetScoreGoalCmd.param:type_name -> Cmd.GoalParam
	12, // 19: Cmd.GetScoreRewardGoalCmd.cmd:type_name -> Cmd.Command
	0,  // 20: Cmd.GetScoreRewardGoalCmd.param:type_name -> Cmd.GoalParam
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_GoalCmd_proto_init() }
func file_GoalCmd_proto_init() {
	if File_GoalCmd_proto != nil {
		return
	}
	file_xCmd_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GoalCmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoalScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GoalCmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoalItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GoalCmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoalGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GoalCmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGoalListGoalCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GoalCmd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGoalItemUpdateGoalCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GoalCmd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGroupUpdateGoalCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GoalCmd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGoalScoreUpdateGoalCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GoalCmd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupRewardGoalCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GoalCmd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoreGoalCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GoalCmd_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoreRewardGoalCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GoalCmd_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GoalCmd_proto_goTypes,
		DependencyIndexes: file_GoalCmd_proto_depIdxs,
		EnumInfos:         file_GoalCmd_proto_enumTypes,
		MessageInfos:      file_GoalCmd_proto_msgTypes,
	}.Build()
	File_GoalCmd_proto = out.File
	file_GoalCmd_proto_rawDesc = nil
	file_GoalCmd_proto_goTypes = nil
	file_GoalCmd_proto_depIdxs = nil
}
