// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v6.33.0
// source: GZoneCmd.proto

package Cmd

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GZoneParam int32

const (
	GZoneParam_GZONEPARAM_UPDATEA_ACTIVE_ONLINE GZoneParam = 1
)

// Enum value maps for GZoneParam.
var (
	GZoneParam_name = map[int32]string{
		1: "GZONEPARAM_UPDATEA_ACTIVE_ONLINE",
	}
	GZoneParam_value = map[string]int32{
		"GZONEPARAM_UPDATEA_ACTIVE_ONLINE": 1,
	}
)

func (x GZoneParam) Enum() *GZoneParam {
	p := new(GZoneParam)
	*p = x
	return p
}

func (x GZoneParam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GZoneParam) Descriptor() protoreflect.EnumDescriptor {
	return file_GZoneCmd_proto_enumTypes[0].Descriptor()
}

func (GZoneParam) Type() protoreflect.EnumType {
	return &file_GZoneCmd_proto_enumTypes[0]
}

func (x GZoneParam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *GZoneParam) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = GZoneParam(num)
	return nil
}

// Deprecated: Use GZoneParam.Descriptor instead.
func (GZoneParam) EnumDescriptor() ([]byte, []int) {
	return file_GZoneCmd_proto_rawDescGZIP(), []int{0}
}

type UpdateActiveOnlineGZoneCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd    *Command    `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=211" json:"cmd,omitempty"`
	Param  *GZoneParam `protobuf:"varint,2,opt,name=param,enum=Cmd.GZoneParam,def=1" json:"param,omitempty"`
	Zoneid *uint32     `protobuf:"varint,3,opt,name=zoneid,def=0" json:"zoneid,omitempty"`
	Active *uint32     `protobuf:"varint,4,opt,name=active,def=0" json:"active,omitempty"`
	Online *uint32     `protobuf:"varint,5,opt,name=online,def=0" json:"online,omitempty"`
}

// Default values for UpdateActiveOnlineGZoneCmd fields.
const (
	Default_UpdateActiveOnlineGZoneCmd_Cmd    = Command_GZONE_PROTOCMD
	Default_UpdateActiveOnlineGZoneCmd_Param  = GZoneParam_GZONEPARAM_UPDATEA_ACTIVE_ONLINE
	Default_UpdateActiveOnlineGZoneCmd_Zoneid = uint32(0)
	Default_UpdateActiveOnlineGZoneCmd_Active = uint32(0)
	Default_UpdateActiveOnlineGZoneCmd_Online = uint32(0)
)

func (x *UpdateActiveOnlineGZoneCmd) Reset() {
	*x = UpdateActiveOnlineGZoneCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GZoneCmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateActiveOnlineGZoneCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActiveOnlineGZoneCmd) ProtoMessage() {}

func (x *UpdateActiveOnlineGZoneCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GZoneCmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActiveOnlineGZoneCmd.ProtoReflect.Descriptor instead.
func (*UpdateActiveOnlineGZoneCmd) Descriptor() ([]byte, []int) {
	return file_GZoneCmd_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateActiveOnlineGZoneCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_UpdateActiveOnlineGZoneCmd_Cmd
}

func (x *UpdateActiveOnlineGZoneCmd) GetParam() GZoneParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_UpdateActiveOnlineGZoneCmd_Param
}

func (x *UpdateActiveOnlineGZoneCmd) GetZoneid() uint32 {
	if x != nil && x.Zoneid != nil {
		return *x.Zoneid
	}
	return Default_UpdateActiveOnlineGZoneCmd_Zoneid
}

func (x *UpdateActiveOnlineGZoneCmd) GetActive() uint32 {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return Default_UpdateActiveOnlineGZoneCmd_Active
}

func (x *UpdateActiveOnlineGZoneCmd) GetOnline() uint32 {
	if x != nil && x.Online != nil {
		return *x.Online
	}
	return Default_UpdateActiveOnlineGZoneCmd_Online
}

var File_GZoneCmd_proto protoreflect.FileDescriptor

var file_GZoneCmd_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x47, 0x5a, 0x6f, 0x6e, 0x65, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x43, 0x6d, 0x64, 0x1a, 0x0a, 0x78, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xe6, 0x01, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x5a, 0x6f, 0x6e, 0x65, 0x43, 0x6d, 0x64,
	0x12, 0x2e, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0e, 0x47, 0x5a, 0x4f,
	0x4e, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64,
	0x12, 0x47, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x47, 0x5a, 0x6f, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x3a, 0x20, 0x47, 0x5a, 0x4f, 0x4e, 0x45, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x55, 0x50, 0x44,
	0x41, 0x54, 0x45, 0x41, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x5f, 0x4f, 0x4e, 0x4c, 0x49,
	0x4e, 0x45, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x19, 0x0a, 0x06, 0x7a, 0x6f, 0x6e,
	0x65, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x30, 0x52, 0x06, 0x7a, 0x6f,
	0x6e, 0x65, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x30, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12,
	0x19, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x3a,
	0x01, 0x30, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2a, 0x32, 0x0a, 0x0a, 0x47, 0x5a,
	0x6f, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x24, 0x0a, 0x20, 0x47, 0x5a, 0x4f, 0x4e,
	0x45, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x41, 0x5f, 0x41,
	0x43, 0x54, 0x49, 0x56, 0x45, 0x5f, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01,
}

var (
	file_GZoneCmd_proto_rawDescOnce sync.Once
	file_GZoneCmd_proto_rawDescData = file_GZoneCmd_proto_rawDesc
)

func file_GZoneCmd_proto_rawDescGZIP() []byte {
	file_GZoneCmd_proto_rawDescOnce.Do(func() {
		file_GZoneCmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_GZoneCmd_proto_rawDescData)
	})
	return file_GZoneCmd_proto_rawDescData
}

var file_GZoneCmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_GZoneCmd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GZoneCmd_proto_goTypes = []interface{}{
	(GZoneParam)(0),                    // 0: Cmd.GZoneParam
	(*UpdateActiveOnlineGZoneCmd)(nil), // 1: Cmd.UpdateActiveOnlineGZoneCmd
	(Command)(0),                       // 2: Cmd.Command
}
var file_GZoneCmd_proto_depIdxs = []int32{
	2, // 0: Cmd.UpdateActiveOnlineGZoneCmd.cmd:type_name -> Cmd.Command
	0, // 1: Cmd.UpdateActiveOnlineGZoneCmd.param:type_name -> Cmd.GZoneParam
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GZoneCmd_proto_init() }
func file_GZoneCmd_proto_init() {
	if File_GZoneCmd_proto != nil {
		return
	}
	file_xCmd_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GZoneCmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateActiveOnlineGZoneCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GZoneCmd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GZoneCmd_proto_goTypes,
		DependencyIndexes: file_GZoneCmd_proto_depIdxs,
		EnumInfos:         file_GZoneCmd_proto_enumTypes,
		MessageInfos:      file_GZoneCmd_proto_msgTypes,
	}.Build()
	File_GZoneCmd_proto = out.File
	file_GZoneCmd_proto_rawDesc = nil
	file_GZoneCmd_proto_goTypes = nil
	file_GZoneCmd_proto_depIdxs = nil
}
