// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v6.33.0
// source: Redis.proto

package Cmd

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ERedisParam int32

const (
	ERedisParam_EREDISPARAM_TEST ERedisParam = 1
)

// Enum value maps for ERedisParam.
var (
	ERedisParam_name = map[int32]string{
		1: "EREDISPARAM_TEST",
	}
	ERedisParam_value = map[string]int32{
		"EREDISPARAM_TEST": 1,
	}
)

func (x ERedisParam) Enum() *ERedisParam {
	p := new(ERedisParam)
	*p = x
	return p
}

func (x ERedisParam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERedisParam) Descriptor() protoreflect.EnumDescriptor {
	return file_Redis_proto_enumTypes[0].Descriptor()
}

func (ERedisParam) Type() protoreflect.EnumType {
	return &file_Redis_proto_enumTypes[0]
}

func (x ERedisParam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ERedisParam) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ERedisParam(num)
	return nil
}

// Deprecated: Use ERedisParam.Descriptor instead.
func (ERedisParam) EnumDescriptor() ([]byte, []int) {
	return file_Redis_proto_rawDescGZIP(), []int{0}
}

type RedisItemTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num *uint32 `protobuf:"varint,1,opt,name=num,def=0" json:"num,omitempty"`
	Str *string `protobuf:"bytes,2,opt,name=str" json:"str,omitempty"`
}

// Default values for RedisItemTest fields.
const (
	Default_RedisItemTest_Num = uint32(0)
)

func (x *RedisItemTest) Reset() {
	*x = RedisItemTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Redis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedisItemTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisItemTest) ProtoMessage() {}

func (x *RedisItemTest) ProtoReflect() protoreflect.Message {
	mi := &file_Redis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisItemTest.ProtoReflect.Descriptor instead.
func (*RedisItemTest) Descriptor() ([]byte, []int) {
	return file_Redis_proto_rawDescGZIP(), []int{0}
}

func (x *RedisItemTest) GetNum() uint32 {
	if x != nil && x.Num != nil {
		return *x.Num
	}
	return Default_RedisItemTest_Num
}

func (x *RedisItemTest) GetStr() string {
	if x != nil && x.Str != nil {
		return *x.Str
	}
	return ""
}

type RedisTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number  *uint32          `protobuf:"varint,1,opt,name=number,def=0" json:"number,omitempty"`
	Str     *string          `protobuf:"bytes,2,opt,name=str" json:"str,omitempty"`
	Numbers []uint32         `protobuf:"varint,3,rep,name=numbers" json:"numbers,omitempty"`
	Strs    []string         `protobuf:"bytes,4,rep,name=strs" json:"strs,omitempty"`
	Item    *RedisItemTest   `protobuf:"bytes,5,opt,name=item" json:"item,omitempty"`
	Items   []*RedisItemTest `protobuf:"bytes,6,rep,name=items" json:"items,omitempty"`
}

// Default values for RedisTest fields.
const (
	Default_RedisTest_Number = uint32(0)
)

func (x *RedisTest) Reset() {
	*x = RedisTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Redis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedisTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisTest) ProtoMessage() {}

func (x *RedisTest) ProtoReflect() protoreflect.Message {
	mi := &file_Redis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisTest.ProtoReflect.Descriptor instead.
func (*RedisTest) Descriptor() ([]byte, []int) {
	return file_Redis_proto_rawDescGZIP(), []int{1}
}

func (x *RedisTest) GetNumber() uint32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return Default_RedisTest_Number
}

func (x *RedisTest) GetStr() string {
	if x != nil && x.Str != nil {
		return *x.Str
	}
	return ""
}

func (x *RedisTest) GetNumbers() []uint32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *RedisTest) GetStrs() []string {
	if x != nil {
		return x.Strs
	}
	return nil
}

func (x *RedisTest) GetItem() *RedisItemTest {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *RedisTest) GetItems() []*RedisItemTest {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_Redis_proto protoreflect.FileDescriptor

var file_Redis_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x52, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x43,
	0x6d, 0x64, 0x22, 0x36, 0x0a, 0x0d, 0x52, 0x65, 0x64, 0x69, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x54,
	0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x3a, 0x01, 0x30, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x22, 0xb8, 0x01, 0x0a, 0x09, 0x52,
	0x65, 0x64, 0x69, 0x73, 0x54, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x30, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x74, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x74, 0x72, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x73, 0x49, 0x74, 0x65,
	0x6d, 0x54, 0x65, 0x73, 0x74, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x28, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x43, 0x6d, 0x64,
	0x2e, 0x52, 0x65, 0x64, 0x69, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x65, 0x73, 0x74, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x2a, 0x23, 0x0a, 0x0b, 0x45, 0x52, 0x65, 0x64, 0x69, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x52, 0x45, 0x44, 0x49, 0x53, 0x50, 0x41,
	0x52, 0x41, 0x4d, 0x5f, 0x54, 0x45, 0x53, 0x54, 0x10, 0x01,
}

var (
	file_Redis_proto_rawDescOnce sync.Once
	file_Redis_proto_rawDescData = file_Redis_proto_rawDesc
)

func file_Redis_proto_rawDescGZIP() []byte {
	file_Redis_proto_rawDescOnce.Do(func() {
		file_Redis_proto_rawDescData = protoimpl.X.CompressGZIP(file_Redis_proto_rawDescData)
	})
	return file_Redis_proto_rawDescData
}

var file_Redis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Redis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Redis_proto_goTypes = []interface{}{
	(ERedisParam)(0),      // 0: Cmd.ERedisParam
	(*RedisItemTest)(nil), // 1: Cmd.RedisItemTest
	(*RedisTest)(nil),     // 2: Cmd.RedisTest
}
var file_Redis_proto_depIdxs = []int32{
	1, // 0: Cmd.RedisTest.item:type_name -> Cmd.RedisItemTest
	1, // 1: Cmd.RedisTest.items:type_name -> Cmd.RedisItemTest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Redis_proto_init() }
func file_Redis_proto_init() {
	if File_Redis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Redis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedisItemTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Redis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedisTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Redis_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Redis_proto_goTypes,
		DependencyIndexes: file_Redis_proto_depIdxs,
		EnumInfos:         file_Redis_proto_enumTypes,
		MessageInfos:      file_Redis_proto_msgTypes,
	}.Build()
	File_Redis_proto = out.File
	file_Redis_proto_rawDesc = nil
	file_Redis_proto_goTypes = nil
	file_Redis_proto_depIdxs = nil
}
