// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v6.33.0
// source: SystemCmd.proto

package Cmd

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SystemParam int32

const (
	SystemParam_HEART_BEAT_SYSCMD     SystemParam = 1
	SystemParam_VERIFY_CONN_SYSCMD    SystemParam = 2
	SystemParam_SERVER_LIST_SYSCMD    SystemParam = 3
	SystemParam_SERVER_INIT_OK_SYSCMD SystemParam = 4
	SystemParam_SERVER_TIME_SYSCMD    SystemParam = 5
	SystemParam_REGIST_REGION_SYSCMD  SystemParam = 6
	SystemParam_COMMON_RELOAD_SYSCMD  SystemParam = 7
	SystemParam_INFO_PROXY_SYSCMD     SystemParam = 8
	SystemParam_REGIST_PROXY_SYSCMD   SystemParam = 9
)

// Enum value maps for SystemParam.
var (
	SystemParam_name = map[int32]string{
		1: "HEART_BEAT_SYSCMD",
		2: "VERIFY_CONN_SYSCMD",
		3: "SERVER_LIST_SYSCMD",
		4: "SERVER_INIT_OK_SYSCMD",
		5: "SERVER_TIME_SYSCMD",
		6: "REGIST_REGION_SYSCMD",
		7: "COMMON_RELOAD_SYSCMD",
		8: "INFO_PROXY_SYSCMD",
		9: "REGIST_PROXY_SYSCMD",
	}
	SystemParam_value = map[string]int32{
		"HEART_BEAT_SYSCMD":     1,
		"VERIFY_CONN_SYSCMD":    2,
		"SERVER_LIST_SYSCMD":    3,
		"SERVER_INIT_OK_SYSCMD": 4,
		"SERVER_TIME_SYSCMD":    5,
		"REGIST_REGION_SYSCMD":  6,
		"COMMON_RELOAD_SYSCMD":  7,
		"INFO_PROXY_SYSCMD":     8,
		"REGIST_PROXY_SYSCMD":   9,
	}
)

func (x SystemParam) Enum() *SystemParam {
	p := new(SystemParam)
	*p = x
	return p
}

func (x SystemParam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemParam) Descriptor() protoreflect.EnumDescriptor {
	return file_SystemCmd_proto_enumTypes[0].Descriptor()
}

func (SystemParam) Type() protoreflect.EnumType {
	return &file_SystemCmd_proto_enumTypes[0]
}

func (x SystemParam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SystemParam) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SystemParam(num)
	return nil
}

// Deprecated: Use SystemParam.Descriptor instead.
func (SystemParam) EnumDescriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{0}
}

type EComLoadType int32

const (
	EComLoadType_EComLoadType_None         EComLoadType = 0
	EComLoadType_EComLoadType_Lua          EComLoadType = 1 //重加载commonlua
	EComLoadType_EComLoadType_BranchConfig EComLoadType = 2 //重加载BranchConfig
	EComLoadType_EComLoadType_Db           EComLoadType = 3 //重加载数据库
)

// Enum value maps for EComLoadType.
var (
	EComLoadType_name = map[int32]string{
		0: "EComLoadType_None",
		1: "EComLoadType_Lua",
		2: "EComLoadType_BranchConfig",
		3: "EComLoadType_Db",
	}
	EComLoadType_value = map[string]int32{
		"EComLoadType_None":         0,
		"EComLoadType_Lua":          1,
		"EComLoadType_BranchConfig": 2,
		"EComLoadType_Db":           3,
	}
)

func (x EComLoadType) Enum() *EComLoadType {
	p := new(EComLoadType)
	*p = x
	return p
}

func (x EComLoadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EComLoadType) Descriptor() protoreflect.EnumDescriptor {
	return file_SystemCmd_proto_enumTypes[1].Descriptor()
}

func (EComLoadType) Type() protoreflect.EnumType {
	return &file_SystemCmd_proto_enumTypes[1]
}

func (x EComLoadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EComLoadType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EComLoadType(num)
	return nil
}

// Deprecated: Use EComLoadType.Descriptor instead.
func (EComLoadType) EnumDescriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{1}
}

type IpPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   *string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port *uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (x *IpPort) Reset() {
	*x = IpPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemCmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpPort) ProtoMessage() {}

func (x *IpPort) ProtoReflect() protoreflect.Message {
	mi := &file_SystemCmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpPort.ProtoReflect.Descriptor instead.
func (*IpPort) Descriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{0}
}

func (x *IpPort) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *IpPort) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

type HeartBeatSystemCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command     `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=255" json:"cmd,omitempty"`
	Param *SystemParam `protobuf:"varint,2,opt,name=param,enum=Cmd.SystemParam,def=1" json:"param,omitempty"`
}

// Default values for HeartBeatSystemCmd fields.
const (
	Default_HeartBeatSystemCmd_Cmd   = Command_SYSTEM_PROTOCMD
	Default_HeartBeatSystemCmd_Param = SystemParam_HEART_BEAT_SYSCMD
)

func (x *HeartBeatSystemCmd) Reset() {
	*x = HeartBeatSystemCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemCmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatSystemCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatSystemCmd) ProtoMessage() {}

func (x *HeartBeatSystemCmd) ProtoReflect() protoreflect.Message {
	mi := &file_SystemCmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatSystemCmd.ProtoReflect.Descriptor instead.
func (*HeartBeatSystemCmd) Descriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{1}
}

func (x *HeartBeatSystemCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_HeartBeatSystemCmd_Cmd
}

func (x *HeartBeatSystemCmd) GetParam() SystemParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_HeartBeatSystemCmd_Param
}

type VerifyConnSystemCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command     `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=255" json:"cmd,omitempty"`
	Param *SystemParam `protobuf:"varint,2,opt,name=param,enum=Cmd.SystemParam,def=2" json:"param,omitempty"`
	Type  *string      `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Name  *string      `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Ret   *bool        `protobuf:"varint,5,opt,name=ret" json:"ret,omitempty"`
}

// Default values for VerifyConnSystemCmd fields.
const (
	Default_VerifyConnSystemCmd_Cmd   = Command_SYSTEM_PROTOCMD
	Default_VerifyConnSystemCmd_Param = SystemParam_VERIFY_CONN_SYSCMD
)

func (x *VerifyConnSystemCmd) Reset() {
	*x = VerifyConnSystemCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemCmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyConnSystemCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyConnSystemCmd) ProtoMessage() {}

func (x *VerifyConnSystemCmd) ProtoReflect() protoreflect.Message {
	mi := &file_SystemCmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyConnSystemCmd.ProtoReflect.Descriptor instead.
func (*VerifyConnSystemCmd) Descriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyConnSystemCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_VerifyConnSystemCmd_Cmd
}

func (x *VerifyConnSystemCmd) GetParam() SystemParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_VerifyConnSystemCmd_Param
}

func (x *VerifyConnSystemCmd) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *VerifyConnSystemCmd) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *VerifyConnSystemCmd) GetRet() bool {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return false
}

type ServerListSystemCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command                    `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=255" json:"cmd,omitempty"`
	Param *SystemParam                `protobuf:"varint,2,opt,name=param,enum=Cmd.SystemParam,def=3" json:"param,omitempty"`
	List  []*ServerListSystemCmd_Item `protobuf:"bytes,3,rep,name=list" json:"list,omitempty"`
}

// Default values for ServerListSystemCmd fields.
const (
	Default_ServerListSystemCmd_Cmd   = Command_SYSTEM_PROTOCMD
	Default_ServerListSystemCmd_Param = SystemParam_SERVER_LIST_SYSCMD
)

func (x *ServerListSystemCmd) Reset() {
	*x = ServerListSystemCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemCmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerListSystemCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerListSystemCmd) ProtoMessage() {}

func (x *ServerListSystemCmd) ProtoReflect() protoreflect.Message {
	mi := &file_SystemCmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerListSystemCmd.ProtoReflect.Descriptor instead.
func (*ServerListSystemCmd) Descriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{3}
}

func (x *ServerListSystemCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_ServerListSystemCmd_Cmd
}

func (x *ServerListSystemCmd) GetParam() SystemParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_ServerListSystemCmd_Param
}

func (x *ServerListSystemCmd) GetList() []*ServerListSystemCmd_Item {
	if x != nil {
		return x.List
	}
	return nil
}

type ServerInitOkConnSystemCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command     `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=255" json:"cmd,omitempty"`
	Param *SystemParam `protobuf:"varint,2,opt,name=param,enum=Cmd.SystemParam,def=4" json:"param,omitempty"`
	Name  *string      `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

// Default values for ServerInitOkConnSystemCmd fields.
const (
	Default_ServerInitOkConnSystemCmd_Cmd   = Command_SYSTEM_PROTOCMD
	Default_ServerInitOkConnSystemCmd_Param = SystemParam_SERVER_INIT_OK_SYSCMD
)

func (x *ServerInitOkConnSystemCmd) Reset() {
	*x = ServerInitOkConnSystemCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemCmd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInitOkConnSystemCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInitOkConnSystemCmd) ProtoMessage() {}

func (x *ServerInitOkConnSystemCmd) ProtoReflect() protoreflect.Message {
	mi := &file_SystemCmd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInitOkConnSystemCmd.ProtoReflect.Descriptor instead.
func (*ServerInitOkConnSystemCmd) Descriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{4}
}

func (x *ServerInitOkConnSystemCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_ServerInitOkConnSystemCmd_Cmd
}

func (x *ServerInitOkConnSystemCmd) GetParam() SystemParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_ServerInitOkConnSystemCmd_Param
}

func (x *ServerInitOkConnSystemCmd) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ServerTimeSystemCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd    *Command     `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=255" json:"cmd,omitempty"`
	Param  *SystemParam `protobuf:"varint,2,opt,name=param,enum=Cmd.SystemParam,def=5" json:"param,omitempty"`
	Adjust *uint32      `protobuf:"varint,3,opt,name=adjust" json:"adjust,omitempty"`
}

// Default values for ServerTimeSystemCmd fields.
const (
	Default_ServerTimeSystemCmd_Cmd   = Command_SYSTEM_PROTOCMD
	Default_ServerTimeSystemCmd_Param = SystemParam_SERVER_TIME_SYSCMD
)

func (x *ServerTimeSystemCmd) Reset() {
	*x = ServerTimeSystemCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemCmd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerTimeSystemCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTimeSystemCmd) ProtoMessage() {}

func (x *ServerTimeSystemCmd) ProtoReflect() protoreflect.Message {
	mi := &file_SystemCmd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTimeSystemCmd.ProtoReflect.Descriptor instead.
func (*ServerTimeSystemCmd) Descriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{5}
}

func (x *ServerTimeSystemCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_ServerTimeSystemCmd_Cmd
}

func (x *ServerTimeSystemCmd) GetParam() SystemParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_ServerTimeSystemCmd_Param
}

func (x *ServerTimeSystemCmd) GetAdjust() uint32 {
	if x != nil && x.Adjust != nil {
		return *x.Adjust
	}
	return 0
}

type RegistRegionSystemCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd        *Command     `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=255" json:"cmd,omitempty"`
	Param      *SystemParam `protobuf:"varint,2,opt,name=param,enum=Cmd.SystemParam,def=6" json:"param,omitempty"`
	Zoneid     *uint32      `protobuf:"varint,3,opt,name=zoneid" json:"zoneid,omitempty"`
	Regiontype *uint32      `protobuf:"varint,4,opt,name=regiontype" json:"regiontype,omitempty"`
	Servertype *uint32      `protobuf:"varint,5,opt,name=servertype" json:"servertype,omitempty"`
	Client     *uint32      `protobuf:"varint,6,opt,name=client" json:"client,omitempty"`
}

// Default values for RegistRegionSystemCmd fields.
const (
	Default_RegistRegionSystemCmd_Cmd   = Command_SYSTEM_PROTOCMD
	Default_RegistRegionSystemCmd_Param = SystemParam_REGIST_REGION_SYSCMD
)

func (x *RegistRegionSystemCmd) Reset() {
	*x = RegistRegionSystemCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemCmd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistRegionSystemCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistRegionSystemCmd) ProtoMessage() {}

func (x *RegistRegionSystemCmd) ProtoReflect() protoreflect.Message {
	mi := &file_SystemCmd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistRegionSystemCmd.ProtoReflect.Descriptor instead.
func (*RegistRegionSystemCmd) Descriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{6}
}

func (x *RegistRegionSystemCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_RegistRegionSystemCmd_Cmd
}

func (x *RegistRegionSystemCmd) GetParam() SystemParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_RegistRegionSystemCmd_Param
}

func (x *RegistRegionSystemCmd) GetZoneid() uint32 {
	if x != nil && x.Zoneid != nil {
		return *x.Zoneid
	}
	return 0
}

func (x *RegistRegionSystemCmd) GetRegiontype() uint32 {
	if x != nil && x.Regiontype != nil {
		return *x.Regiontype
	}
	return 0
}

func (x *RegistRegionSystemCmd) GetServertype() uint32 {
	if x != nil && x.Servertype != nil {
		return *x.Servertype
	}
	return 0
}

func (x *RegistRegionSystemCmd) GetClient() uint32 {
	if x != nil && x.Client != nil {
		return *x.Client
	}
	return 0
}

type CommonReloadSystemCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command      `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=255" json:"cmd,omitempty"`
	Param *SystemParam  `protobuf:"varint,2,opt,name=param,enum=Cmd.SystemParam,def=7" json:"param,omitempty"`
	Type  *EComLoadType `protobuf:"varint,3,opt,name=type,enum=Cmd.EComLoadType" json:"type,omitempty"`
}

// Default values for CommonReloadSystemCmd fields.
const (
	Default_CommonReloadSystemCmd_Cmd   = Command_SYSTEM_PROTOCMD
	Default_CommonReloadSystemCmd_Param = SystemParam_COMMON_RELOAD_SYSCMD
)

func (x *CommonReloadSystemCmd) Reset() {
	*x = CommonReloadSystemCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemCmd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonReloadSystemCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonReloadSystemCmd) ProtoMessage() {}

func (x *CommonReloadSystemCmd) ProtoReflect() protoreflect.Message {
	mi := &file_SystemCmd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonReloadSystemCmd.ProtoReflect.Descriptor instead.
func (*CommonReloadSystemCmd) Descriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{7}
}

func (x *CommonReloadSystemCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_CommonReloadSystemCmd_Cmd
}

func (x *CommonReloadSystemCmd) GetParam() SystemParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_CommonReloadSystemCmd_Param
}

func (x *CommonReloadSystemCmd) GetType() EComLoadType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return EComLoadType_EComLoadType_None
}

type InfoProxySystemCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd     *Command     `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=255" json:"cmd,omitempty"`
	Param   *SystemParam `protobuf:"varint,2,opt,name=param,enum=Cmd.SystemParam,def=8" json:"param,omitempty"`
	Proxyid *string      `protobuf:"bytes,3,opt,name=proxyid" json:"proxyid,omitempty"`
	Tasknum *uint32      `protobuf:"varint,4,opt,name=tasknum" json:"tasknum,omitempty"`
}

// Default values for InfoProxySystemCmd fields.
const (
	Default_InfoProxySystemCmd_Cmd   = Command_SYSTEM_PROTOCMD
	Default_InfoProxySystemCmd_Param = SystemParam_INFO_PROXY_SYSCMD
)

func (x *InfoProxySystemCmd) Reset() {
	*x = InfoProxySystemCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemCmd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoProxySystemCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoProxySystemCmd) ProtoMessage() {}

func (x *InfoProxySystemCmd) ProtoReflect() protoreflect.Message {
	mi := &file_SystemCmd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoProxySystemCmd.ProtoReflect.Descriptor instead.
func (*InfoProxySystemCmd) Descriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{8}
}

func (x *InfoProxySystemCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_InfoProxySystemCmd_Cmd
}

func (x *InfoProxySystemCmd) GetParam() SystemParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_InfoProxySystemCmd_Param
}

func (x *InfoProxySystemCmd) GetProxyid() string {
	if x != nil && x.Proxyid != nil {
		return *x.Proxyid
	}
	return ""
}

func (x *InfoProxySystemCmd) GetTasknum() uint32 {
	if x != nil && x.Tasknum != nil {
		return *x.Tasknum
	}
	return 0
}

type RegistProxySystemCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd     *Command     `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=255" json:"cmd,omitempty"`
	Param   *SystemParam `protobuf:"varint,2,opt,name=param,enum=Cmd.SystemParam,def=9" json:"param,omitempty"`
	Proxyid *string      `protobuf:"bytes,3,opt,name=proxyid" json:"proxyid,omitempty"`
}

// Default values for RegistProxySystemCmd fields.
const (
	Default_RegistProxySystemCmd_Cmd   = Command_SYSTEM_PROTOCMD
	Default_RegistProxySystemCmd_Param = SystemParam_REGIST_PROXY_SYSCMD
)

func (x *RegistProxySystemCmd) Reset() {
	*x = RegistProxySystemCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemCmd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistProxySystemCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistProxySystemCmd) ProtoMessage() {}

func (x *RegistProxySystemCmd) ProtoReflect() protoreflect.Message {
	mi := &file_SystemCmd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistProxySystemCmd.ProtoReflect.Descriptor instead.
func (*RegistProxySystemCmd) Descriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{9}
}

func (x *RegistProxySystemCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_RegistProxySystemCmd_Cmd
}

func (x *RegistProxySystemCmd) GetParam() SystemParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_RegistProxySystemCmd_Param
}

func (x *RegistProxySystemCmd) GetProxyid() string {
	if x != nil && x.Proxyid != nil {
		return *x.Proxyid
	}
	return ""
}

type ServerListSystemCmd_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Name *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Ip   *string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
	Port *uint32 `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
}

func (x *ServerListSystemCmd_Item) Reset() {
	*x = ServerListSystemCmd_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemCmd_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerListSystemCmd_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerListSystemCmd_Item) ProtoMessage() {}

func (x *ServerListSystemCmd_Item) ProtoReflect() protoreflect.Message {
	mi := &file_SystemCmd_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerListSystemCmd_Item.ProtoReflect.Descriptor instead.
func (*ServerListSystemCmd_Item) Descriptor() ([]byte, []int) {
	return file_SystemCmd_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ServerListSystemCmd_Item) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ServerListSystemCmd_Item) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ServerListSystemCmd_Item) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *ServerListSystemCmd_Item) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

var File_SystemCmd_proto protoreflect.FileDescriptor

var file_SystemCmd_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x43, 0x6d, 0x64, 0x1a, 0x0a, 0x78, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x06, 0x49, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0x80, 0x01, 0x0a, 0x12, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x43, 0x6d, 0x64, 0x12, 0x2f, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x3a, 0x0f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f,
	0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x39, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x11, 0x48, 0x45, 0x41, 0x52, 0x54,
	0x5f, 0x42, 0x45, 0x41, 0x54, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d, 0x44, 0x52, 0x05, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x22, 0xbc, 0x01, 0x0a, 0x13, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f,
	0x6e, 0x6e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6d, 0x64, 0x12, 0x2f, 0x0a, 0x03, 0x63,
	0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x50,
	0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x3a, 0x0a, 0x05,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x43, 0x6d,
	0x64, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x12, 0x56,
	0x45, 0x52, 0x49, 0x46, 0x59, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d,
	0x44, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72,
	0x65, 0x74, 0x22, 0x89, 0x02, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6d, 0x64, 0x12, 0x2f, 0x0a, 0x03, 0x63, 0x6d,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x50, 0x52,
	0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x3a, 0x0a, 0x05, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x43, 0x6d, 0x64,
	0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x12, 0x53, 0x45,
	0x52, 0x56, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d, 0x44,
	0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x31, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6d, 0x64, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x52, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x9f,
	0x01, 0x0a, 0x19, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x4f, 0x6b, 0x43,
	0x6f, 0x6e, 0x6e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6d, 0x64, 0x12, 0x2f, 0x0a, 0x03,
	0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f,
	0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x3d, 0x0a,
	0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x43,
	0x6d, 0x64, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x15,
	0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x49, 0x4e, 0x49, 0x54, 0x5f, 0x4f, 0x4b, 0x5f, 0x53,
	0x59, 0x53, 0x43, 0x4d, 0x44, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x9a, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6d, 0x64, 0x12, 0x2f, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x3a, 0x0f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x54,
	0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x3a, 0x0a, 0x05, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x12, 0x53, 0x45, 0x52, 0x56,
	0x45, 0x52, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d, 0x44, 0x52, 0x05,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x22, 0xf6, 0x01,
	0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x43, 0x6d, 0x64, 0x12, 0x2f, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x3a, 0x0f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f,
	0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x3c, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x14, 0x52, 0x45, 0x47, 0x49, 0x53,
	0x54, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d, 0x44, 0x52,
	0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0xad, 0x01, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6d, 0x64,
	0x12, 0x2f, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0f, 0x53, 0x59, 0x53,
	0x54, 0x45, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d,
	0x64, 0x12, 0x3c, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x3a, 0x14, 0x43, 0x4f, 0x4d, 0x4d, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x4c, 0x4f, 0x41,
	0x44, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d, 0x44, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x43, 0x6d, 0x64, 0x2e, 0x45, 0x43, 0x6f, 0x6d, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xb4, 0x01, 0x0a, 0x12, 0x49, 0x6e, 0x66, 0x6f, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6d, 0x64, 0x12, 0x2f, 0x0a,
	0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x0f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d,
	0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x39,
	0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x43, 0x6d, 0x64, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a,
	0x11, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x53, 0x59, 0x53, 0x43,
	0x4d, 0x44, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x6e, 0x75, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x6e, 0x75, 0x6d, 0x22, 0x9e, 0x01,
	0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x43, 0x6d, 0x64, 0x12, 0x2f, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x3a, 0x0f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43,
	0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x3b, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x13, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54,
	0x5f, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d, 0x44, 0x52, 0x05, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x69, 0x64, 0x2a, 0xeb,
	0x01, 0x0a, 0x0b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x15,
	0x0a, 0x11, 0x48, 0x45, 0x41, 0x52, 0x54, 0x5f, 0x42, 0x45, 0x41, 0x54, 0x5f, 0x53, 0x59, 0x53,
	0x43, 0x4d, 0x44, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x56, 0x45, 0x52, 0x49, 0x46, 0x59, 0x5f,
	0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d, 0x44, 0x10, 0x02, 0x12, 0x16, 0x0a,
	0x12, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x53, 0x59, 0x53,
	0x43, 0x4d, 0x44, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f,
	0x49, 0x4e, 0x49, 0x54, 0x5f, 0x4f, 0x4b, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d, 0x44, 0x10, 0x04,
	0x12, 0x16, 0x0a, 0x12, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f,
	0x53, 0x59, 0x53, 0x43, 0x4d, 0x44, 0x10, 0x05, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x45, 0x47, 0x49,
	0x53, 0x54, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d, 0x44,
	0x10, 0x06, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4f, 0x4d, 0x4d, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x4c,
	0x4f, 0x41, 0x44, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d, 0x44, 0x10, 0x07, 0x12, 0x15, 0x0a, 0x11,
	0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d,
	0x44, 0x10, 0x08, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x5f, 0x50, 0x52,
	0x4f, 0x58, 0x59, 0x5f, 0x53, 0x59, 0x53, 0x43, 0x4d, 0x44, 0x10, 0x09, 0x2a, 0x6f, 0x0a, 0x0c,
	0x45, 0x43, 0x6f, 0x6d, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11,
	0x45, 0x43, 0x6f, 0x6d, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x43, 0x6f, 0x6d, 0x4c, 0x6f, 0x61, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x4c, 0x75, 0x61, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x45, 0x43, 0x6f,
	0x6d, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x43, 0x6f, 0x6d,
	0x4c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x44, 0x62, 0x10, 0x03,
}

var (
	file_SystemCmd_proto_rawDescOnce sync.Once
	file_SystemCmd_proto_rawDescData = file_SystemCmd_proto_rawDesc
)

func file_SystemCmd_proto_rawDescGZIP() []byte {
	file_SystemCmd_proto_rawDescOnce.Do(func() {
		file_SystemCmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_SystemCmd_proto_rawDescData)
	})
	return file_SystemCmd_proto_rawDescData
}

var file_SystemCmd_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_SystemCmd_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_SystemCmd_proto_goTypes = []interface{}{
	(SystemParam)(0),                  // 0: Cmd.SystemParam
	(EComLoadType)(0),                 // 1: Cmd.EComLoadType
	(*IpPort)(nil),                    // 2: Cmd.IpPort
	(*HeartBeatSystemCmd)(nil),        // 3: Cmd.HeartBeatSystemCmd
	(*VerifyConnSystemCmd)(nil),       // 4: Cmd.VerifyConnSystemCmd
	(*ServerListSystemCmd)(nil),       // 5: Cmd.ServerListSystemCmd
	(*ServerInitOkConnSystemCmd)(nil), // 6: Cmd.ServerInitOkConnSystemCmd
	(*ServerTimeSystemCmd)(nil),       // 7: Cmd.ServerTimeSystemCmd
	(*RegistRegionSystemCmd)(nil),     // 8: Cmd.RegistRegionSystemCmd
	(*CommonReloadSystemCmd)(nil),     // 9: Cmd.CommonReloadSystemCmd
	(*InfoProxySystemCmd)(nil),        // 10: Cmd.InfoProxySystemCmd
	(*RegistProxySystemCmd)(nil),      // 11: Cmd.RegistProxySystemCmd
	(*ServerListSystemCmd_Item)(nil),  // 12: Cmd.ServerListSystemCmd.Item
	(Command)(0),                      // 13: Cmd.Command
}
var file_SystemCmd_proto_depIdxs = []int32{
	13, // 0: Cmd.HeartBeatSystemCmd.cmd:type_name -> Cmd.Command
	0,  // 1: Cmd.HeartBeatSystemCmd.param:type_name -> Cmd.SystemParam
	13, // 2: Cmd.VerifyConnSystemCmd.cmd:type_name -> Cmd.Command
	0,  // 3: Cmd.VerifyConnSystemCmd.param:type_name -> Cmd.SystemParam
	13, // 4: Cmd.ServerListSystemCmd.cmd:type_name -> Cmd.Command
	0,  // 5: Cmd.ServerListSystemCmd.param:type_name -> Cmd.SystemParam
	12, // 6: Cmd.ServerListSystemCmd.list:type_name -> Cmd.ServerListSystemCmd.Item
	13, // 7: Cmd.ServerInitOkConnSystemCmd.cmd:type_name -> Cmd.Command
	0,  // 8: Cmd.ServerInitOkConnSystemCmd.param:type_name -> Cmd.SystemParam
	13, // 9: Cmd.ServerTimeSystemCmd.cmd:type_name -> Cmd.Command
	0,  // 10: Cmd.ServerTimeSystemCmd.param:type_name -> Cmd.SystemParam
	13, // 11: Cmd.RegistRegionSystemCmd.cmd:type_name -> Cmd.Command
	0,  // 12: Cmd.RegistRegionSystemCmd.param:type_name -> Cmd.SystemParam
	13, // 13: Cmd.CommonReloadSystemCmd.cmd:type_name -> Cmd.Command
	0,  // 14: Cmd.CommonReloadSystemCmd.param:type_name -> Cmd.SystemParam
	1,  // 15: Cmd.CommonReloadSystemCmd.type:type_name -> Cmd.EComLoadType
	13, // 16: Cmd.InfoProxySystemCmd.cmd:type_name -> Cmd.Command
	0,  // 17: Cmd.InfoProxySystemCmd.param:type_name -> Cmd.SystemParam
	13, // 18: Cmd.RegistProxySystemCmd.cmd:type_name -> Cmd.Command
	0,  // 19: Cmd.RegistProxySystemCmd.param:type_name -> Cmd.SystemParam
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_SystemCmd_proto_init() }
func file_SystemCmd_proto_init() {
	if File_SystemCmd_proto != nil {
		return
	}
	file_xCmd_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SystemCmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemCmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatSystemCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemCmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyConnSystemCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemCmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerListSystemCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemCmd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInitOkConnSystemCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemCmd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerTimeSystemCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemCmd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistRegionSystemCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemCmd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonReloadSystemCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemCmd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoProxySystemCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemCmd_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistProxySystemCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemCmd_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerListSystemCmd_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SystemCmd_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SystemCmd_proto_goTypes,
		DependencyIndexes: file_SystemCmd_proto_depIdxs,
		EnumInfos:         file_SystemCmd_proto_enumTypes,
		MessageInfos:      file_SystemCmd_proto_msgTypes,
	}.Build()
	File_SystemCmd_proto = out.File
	file_SystemCmd_proto_rawDesc = nil
	file_SystemCmd_proto_goTypes = nil
	file_SystemCmd_proto_depIdxs = nil
}
