// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: Tutor.proto

package Cmd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TutorParam int32

const (
	TutorParam_TUTORPARAM_TASK_UPDATE_NTF     TutorParam = 1
	TutorParam_TUTORPARAM_TASK_QUERY          TutorParam = 2
	TutorParam_TUTORPARAM_TASK_TEACHER_REWARD TutorParam = 3
	TutorParam_TUTORPARAM_GROW_REWARD_UPDATE  TutorParam = 4
	TutorParam_TUTORPARAM_GET_GROW_REWARD     TutorParam = 5
	TutorParam_TUTORPARAM_TASK_UPDATE_BOX     TutorParam = 6
)

// Enum value maps for TutorParam.
var (
	TutorParam_name = map[int32]string{
		1: "TUTORPARAM_TASK_UPDATE_NTF",
		2: "TUTORPARAM_TASK_QUERY",
		3: "TUTORPARAM_TASK_TEACHER_REWARD",
		4: "TUTORPARAM_GROW_REWARD_UPDATE",
		5: "TUTORPARAM_GET_GROW_REWARD",
		6: "TUTORPARAM_TASK_UPDATE_BOX",
	}
	TutorParam_value = map[string]int32{
		"TUTORPARAM_TASK_UPDATE_NTF":     1,
		"TUTORPARAM_TASK_QUERY":          2,
		"TUTORPARAM_TASK_TEACHER_REWARD": 3,
		"TUTORPARAM_GROW_REWARD_UPDATE":  4,
		"TUTORPARAM_GET_GROW_REWARD":     5,
		"TUTORPARAM_TASK_UPDATE_BOX":     6,
	}
)

func (x TutorParam) Enum() *TutorParam {
	p := new(TutorParam)
	*p = x
	return p
}

func (x TutorParam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TutorParam) Descriptor() protoreflect.EnumDescriptor {
	return file_Tutor_proto_enumTypes[0].Descriptor()
}

func (TutorParam) Type() protoreflect.EnumType {
	return &file_Tutor_proto_enumTypes[0]
}

func (x TutorParam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TutorParam) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TutorParam(num)
	return nil
}

// Deprecated: Use TutorParam.Descriptor instead.
func (TutorParam) EnumDescriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{0}
}

type TutorTaskItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *uint32 `protobuf:"varint,1,opt,name=id,def=0" json:"id,omitempty"`
	Progress *uint32 `protobuf:"varint,2,opt,name=progress,def=0" json:"progress,omitempty"`
	Reward   *bool   `protobuf:"varint,3,opt,name=reward,def=0" json:"reward,omitempty"`
}

// Default values for TutorTaskItem fields.
const (
	Default_TutorTaskItem_Id       = uint32(0)
	Default_TutorTaskItem_Progress = uint32(0)
	Default_TutorTaskItem_Reward   = bool(false)
)

func (x *TutorTaskItem) Reset() {
	*x = TutorTaskItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tutor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorTaskItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorTaskItem) ProtoMessage() {}

func (x *TutorTaskItem) ProtoReflect() protoreflect.Message {
	mi := &file_Tutor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorTaskItem.ProtoReflect.Descriptor instead.
func (*TutorTaskItem) Descriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{0}
}

func (x *TutorTaskItem) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_TutorTaskItem_Id
}

func (x *TutorTaskItem) GetProgress() uint32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return Default_TutorTaskItem_Progress
}

func (x *TutorTaskItem) GetReward() bool {
	if x != nil && x.Reward != nil {
		return *x.Reward
	}
	return Default_TutorTaskItem_Reward
}

type TutorRewardItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Taskid *uint32 `protobuf:"varint,1,opt,name=taskid" json:"taskid,omitempty"`
	Time   *uint32 `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
}

func (x *TutorRewardItem) Reset() {
	*x = TutorRewardItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tutor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorRewardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorRewardItem) ProtoMessage() {}

func (x *TutorRewardItem) ProtoReflect() protoreflect.Message {
	mi := &file_Tutor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorRewardItem.ProtoReflect.Descriptor instead.
func (*TutorRewardItem) Descriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{1}
}

func (x *TutorRewardItem) GetTaskid() uint32 {
	if x != nil && x.Taskid != nil {
		return *x.Taskid
	}
	return 0
}

func (x *TutorRewardItem) GetTime() uint32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

type TutorReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Charid *uint64            `protobuf:"varint,1,opt,name=charid,def=0" json:"charid,omitempty"`
	Name   *string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Reward []uint32           `protobuf:"varint,3,rep,name=reward" json:"reward,omitempty"`
	Item   []*TutorRewardItem `protobuf:"bytes,4,rep,name=item" json:"item,omitempty"`
}

// Default values for TutorReward fields.
const (
	Default_TutorReward_Charid = uint64(0)
)

func (x *TutorReward) Reset() {
	*x = TutorReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tutor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorReward) ProtoMessage() {}

func (x *TutorReward) ProtoReflect() protoreflect.Message {
	mi := &file_Tutor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorReward.ProtoReflect.Descriptor instead.
func (*TutorReward) Descriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{2}
}

func (x *TutorReward) GetCharid() uint64 {
	if x != nil && x.Charid != nil {
		return *x.Charid
	}
	return Default_TutorReward_Charid
}

func (x *TutorReward) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TutorReward) GetReward() []uint32 {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *TutorReward) GetItem() []*TutorRewardItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type OfflineTutorReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teacherrewards []*TutorReward `protobuf:"bytes,1,rep,name=teacherrewards" json:"teacherrewards,omitempty"`
}

func (x *OfflineTutorReward) Reset() {
	*x = OfflineTutorReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tutor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineTutorReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineTutorReward) ProtoMessage() {}

func (x *OfflineTutorReward) ProtoReflect() protoreflect.Message {
	mi := &file_Tutor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineTutorReward.ProtoReflect.Descriptor instead.
func (*OfflineTutorReward) Descriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{3}
}

func (x *OfflineTutorReward) GetTeacherrewards() []*TutorReward {
	if x != nil {
		return x.Teacherrewards
	}
	return nil
}

type TutorTaskUpdateNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command         `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=31" json:"cmd,omitempty"`
	Param *TutorParam      `protobuf:"varint,2,opt,name=param,enum=Cmd.TutorParam,def=1" json:"param,omitempty"`
	Items []*TutorTaskItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
}

// Default values for TutorTaskUpdateNtf fields.
const (
	Default_TutorTaskUpdateNtf_Cmd   = Command_SCENE_USER_TUTOR_PROTOCMD
	Default_TutorTaskUpdateNtf_Param = TutorParam_TUTORPARAM_TASK_UPDATE_NTF
)

func (x *TutorTaskUpdateNtf) Reset() {
	*x = TutorTaskUpdateNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tutor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorTaskUpdateNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorTaskUpdateNtf) ProtoMessage() {}

func (x *TutorTaskUpdateNtf) ProtoReflect() protoreflect.Message {
	mi := &file_Tutor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorTaskUpdateNtf.ProtoReflect.Descriptor instead.
func (*TutorTaskUpdateNtf) Descriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{4}
}

func (x *TutorTaskUpdateNtf) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_TutorTaskUpdateNtf_Cmd
}

func (x *TutorTaskUpdateNtf) GetParam() TutorParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_TutorTaskUpdateNtf_Param
}

func (x *TutorTaskUpdateNtf) GetItems() []*TutorTaskItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TutorTaskQueryCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd           *Command         `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=31" json:"cmd,omitempty"`
	Param         *TutorParam      `protobuf:"varint,2,opt,name=param,enum=Cmd.TutorParam,def=2" json:"param,omitempty"`
	Charid        *uint64          `protobuf:"varint,3,opt,name=charid,def=0" json:"charid,omitempty"`
	Items         []*TutorTaskItem `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	Finishtaskids []uint32         `protobuf:"varint,5,rep,name=finishtaskids" json:"finishtaskids,omitempty"`
	Refresh       *bool            `protobuf:"varint,6,opt,name=refresh,def=0" json:"refresh,omitempty"`
}

// Default values for TutorTaskQueryCmd fields.
const (
	Default_TutorTaskQueryCmd_Cmd     = Command_SCENE_USER_TUTOR_PROTOCMD
	Default_TutorTaskQueryCmd_Param   = TutorParam_TUTORPARAM_TASK_QUERY
	Default_TutorTaskQueryCmd_Charid  = uint64(0)
	Default_TutorTaskQueryCmd_Refresh = bool(false)
)

func (x *TutorTaskQueryCmd) Reset() {
	*x = TutorTaskQueryCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tutor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorTaskQueryCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorTaskQueryCmd) ProtoMessage() {}

func (x *TutorTaskQueryCmd) ProtoReflect() protoreflect.Message {
	mi := &file_Tutor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorTaskQueryCmd.ProtoReflect.Descriptor instead.
func (*TutorTaskQueryCmd) Descriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{5}
}

func (x *TutorTaskQueryCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_TutorTaskQueryCmd_Cmd
}

func (x *TutorTaskQueryCmd) GetParam() TutorParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_TutorTaskQueryCmd_Param
}

func (x *TutorTaskQueryCmd) GetCharid() uint64 {
	if x != nil && x.Charid != nil {
		return *x.Charid
	}
	return Default_TutorTaskQueryCmd_Charid
}

func (x *TutorTaskQueryCmd) GetItems() []*TutorTaskItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TutorTaskQueryCmd) GetFinishtaskids() []uint32 {
	if x != nil {
		return x.Finishtaskids
	}
	return nil
}

func (x *TutorTaskQueryCmd) GetRefresh() bool {
	if x != nil && x.Refresh != nil {
		return *x.Refresh
	}
	return Default_TutorTaskQueryCmd_Refresh
}

type TutorTaskTeacherRewardCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd    *Command    `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=31" json:"cmd,omitempty"`
	Param  *TutorParam `protobuf:"varint,2,opt,name=param,enum=Cmd.TutorParam,def=3" json:"param,omitempty"`
	Charid *uint64     `protobuf:"varint,3,opt,name=charid,def=0" json:"charid,omitempty"`
	Taskid *uint32     `protobuf:"varint,4,opt,name=taskid,def=0" json:"taskid,omitempty"`
}

// Default values for TutorTaskTeacherRewardCmd fields.
const (
	Default_TutorTaskTeacherRewardCmd_Cmd    = Command_SCENE_USER_TUTOR_PROTOCMD
	Default_TutorTaskTeacherRewardCmd_Param  = TutorParam_TUTORPARAM_TASK_TEACHER_REWARD
	Default_TutorTaskTeacherRewardCmd_Charid = uint64(0)
	Default_TutorTaskTeacherRewardCmd_Taskid = uint32(0)
)

func (x *TutorTaskTeacherRewardCmd) Reset() {
	*x = TutorTaskTeacherRewardCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tutor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorTaskTeacherRewardCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorTaskTeacherRewardCmd) ProtoMessage() {}

func (x *TutorTaskTeacherRewardCmd) ProtoReflect() protoreflect.Message {
	mi := &file_Tutor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorTaskTeacherRewardCmd.ProtoReflect.Descriptor instead.
func (*TutorTaskTeacherRewardCmd) Descriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{6}
}

func (x *TutorTaskTeacherRewardCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_TutorTaskTeacherRewardCmd_Cmd
}

func (x *TutorTaskTeacherRewardCmd) GetParam() TutorParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_TutorTaskTeacherRewardCmd_Param
}

func (x *TutorTaskTeacherRewardCmd) GetCharid() uint64 {
	if x != nil && x.Charid != nil {
		return *x.Charid
	}
	return Default_TutorTaskTeacherRewardCmd_Charid
}

func (x *TutorTaskTeacherRewardCmd) GetTaskid() uint32 {
	if x != nil && x.Taskid != nil {
		return *x.Taskid
	}
	return Default_TutorTaskTeacherRewardCmd_Taskid
}

type TutorGrowRewardUpdateNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd         *Command    `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=31" json:"cmd,omitempty"`
	Param       *TutorParam `protobuf:"varint,2,opt,name=param,enum=Cmd.TutorParam,def=4" json:"param,omitempty"`
	Growrewards []uint64    `protobuf:"varint,3,rep,name=growrewards" json:"growrewards,omitempty"`
}

// Default values for TutorGrowRewardUpdateNtf fields.
const (
	Default_TutorGrowRewardUpdateNtf_Cmd   = Command_SCENE_USER_TUTOR_PROTOCMD
	Default_TutorGrowRewardUpdateNtf_Param = TutorParam_TUTORPARAM_GROW_REWARD_UPDATE
)

func (x *TutorGrowRewardUpdateNtf) Reset() {
	*x = TutorGrowRewardUpdateNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tutor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorGrowRewardUpdateNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorGrowRewardUpdateNtf) ProtoMessage() {}

func (x *TutorGrowRewardUpdateNtf) ProtoReflect() protoreflect.Message {
	mi := &file_Tutor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorGrowRewardUpdateNtf.ProtoReflect.Descriptor instead.
func (*TutorGrowRewardUpdateNtf) Descriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{7}
}

func (x *TutorGrowRewardUpdateNtf) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_TutorGrowRewardUpdateNtf_Cmd
}

func (x *TutorGrowRewardUpdateNtf) GetParam() TutorParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_TutorGrowRewardUpdateNtf_Param
}

func (x *TutorGrowRewardUpdateNtf) GetGrowrewards() []uint64 {
	if x != nil {
		return x.Growrewards
	}
	return nil
}

type TutorGetGrowRewardCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command    `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=31" json:"cmd,omitempty"`
	Param *TutorParam `protobuf:"varint,2,opt,name=param,enum=Cmd.TutorParam,def=5" json:"param,omitempty"`
}

// Default values for TutorGetGrowRewardCmd fields.
const (
	Default_TutorGetGrowRewardCmd_Cmd   = Command_SCENE_USER_TUTOR_PROTOCMD
	Default_TutorGetGrowRewardCmd_Param = TutorParam_TUTORPARAM_GET_GROW_REWARD
)

func (x *TutorGetGrowRewardCmd) Reset() {
	*x = TutorGetGrowRewardCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tutor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorGetGrowRewardCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorGetGrowRewardCmd) ProtoMessage() {}

func (x *TutorGetGrowRewardCmd) ProtoReflect() protoreflect.Message {
	mi := &file_Tutor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorGetGrowRewardCmd.ProtoReflect.Descriptor instead.
func (*TutorGetGrowRewardCmd) Descriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{8}
}

func (x *TutorGetGrowRewardCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_TutorGetGrowRewardCmd_Cmd
}

func (x *TutorGetGrowRewardCmd) GetParam() TutorParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_TutorGetGrowRewardCmd_Param
}

type TutorBoxItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Itemid *uint32 `protobuf:"varint,1,opt,name=itemid" json:"itemid,omitempty"`
	Count  *uint32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (x *TutorBoxItem) Reset() {
	*x = TutorBoxItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tutor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorBoxItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorBoxItem) ProtoMessage() {}

func (x *TutorBoxItem) ProtoReflect() protoreflect.Message {
	mi := &file_Tutor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorBoxItem.ProtoReflect.Descriptor instead.
func (*TutorBoxItem) Descriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{9}
}

func (x *TutorBoxItem) GetItemid() uint32 {
	if x != nil && x.Itemid != nil {
		return *x.Itemid
	}
	return 0
}

func (x *TutorBoxItem) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type TutorTaskUpdateBoxCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   *Command        `protobuf:"varint,1,opt,name=cmd,enum=Cmd.Command,def=31" json:"cmd,omitempty"`
	Param *TutorParam     `protobuf:"varint,2,opt,name=param,enum=Cmd.TutorParam,def=6" json:"param,omitempty"`
	Items []*TutorBoxItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
}

// Default values for TutorTaskUpdateBoxCmd fields.
const (
	Default_TutorTaskUpdateBoxCmd_Cmd   = Command_SCENE_USER_TUTOR_PROTOCMD
	Default_TutorTaskUpdateBoxCmd_Param = TutorParam_TUTORPARAM_TASK_UPDATE_BOX
)

func (x *TutorTaskUpdateBoxCmd) Reset() {
	*x = TutorTaskUpdateBoxCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tutor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorTaskUpdateBoxCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorTaskUpdateBoxCmd) ProtoMessage() {}

func (x *TutorTaskUpdateBoxCmd) ProtoReflect() protoreflect.Message {
	mi := &file_Tutor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorTaskUpdateBoxCmd.ProtoReflect.Descriptor instead.
func (*TutorTaskUpdateBoxCmd) Descriptor() ([]byte, []int) {
	return file_Tutor_proto_rawDescGZIP(), []int{10}
}

func (x *TutorTaskUpdateBoxCmd) GetCmd() Command {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return Default_TutorTaskUpdateBoxCmd_Cmd
}

func (x *TutorTaskUpdateBoxCmd) GetParam() TutorParam {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return Default_TutorTaskUpdateBoxCmd_Param
}

func (x *TutorTaskUpdateBoxCmd) GetItems() []*TutorBoxItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_Tutor_proto protoreflect.FileDescriptor

var file_Tutor_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x43,
	0x6d, 0x64, 0x1a, 0x0a, 0x78, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60,
	0x0a, 0x0d, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x11, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x30, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x30, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1d, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x22, 0x3d, 0x0a, 0x0f, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22,
	0x7e, 0x0a, 0x0b, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x19,
	0x0a, 0x06, 0x63, 0x68, 0x61, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x3a, 0x01,
	0x30, 0x52, 0x06, 0x63, 0x68, 0x61, 0x72, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22,
	0x4e, 0x0a, 0x12, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x38, 0x0a, 0x0e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x43, 0x6d, 0x64, 0x2e, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52,
	0x0e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x22,
	0xbc, 0x01, 0x0a, 0x12, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4e, 0x74, 0x66, 0x12, 0x39, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x3a, 0x19, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x54, 0x55,
	0x54, 0x4f, 0x52, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d,
	0x64, 0x12, 0x41, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x3a, 0x1a, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x54, 0x41,
	0x53, 0x4b, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x4e, 0x54, 0x46, 0x52, 0x05, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x28, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x54,
	0x61, 0x73, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x98,
	0x02, 0x0a, 0x11, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x43, 0x6d, 0x64, 0x12, 0x39, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a,
	0x19, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x54, 0x55, 0x54, 0x4f,
	0x52, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12,
	0x3c, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a,
	0x15, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x54, 0x41, 0x53, 0x4b,
	0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x19, 0x0a,
	0x06, 0x63, 0x68, 0x61, 0x72, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x3a, 0x01, 0x30,
	0x52, 0x06, 0x63, 0x68, 0x61, 0x72, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x54, 0x75,
	0x74, 0x6f, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x74, 0x61, 0x73, 0x6b,
	0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0d, 0x66, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x74, 0x61, 0x73, 0x6b, 0x69, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x07, 0x72, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65,
	0x52, 0x07, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x22, 0xd3, 0x01, 0x0a, 0x19, 0x54, 0x75,
	0x74, 0x6f, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x43, 0x6d, 0x64, 0x12, 0x39, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x3a, 0x19, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x54,
	0x55, 0x54, 0x4f, 0x52, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63,
	0x6d, 0x64, 0x12, 0x45, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x3a, 0x1e, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x54,
	0x41, 0x53, 0x4b, 0x5f, 0x54, 0x45, 0x41, 0x43, 0x48, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x57, 0x41,
	0x52, 0x44, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x19, 0x0a, 0x06, 0x63, 0x68, 0x61,
	0x72, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x3a, 0x01, 0x30, 0x52, 0x06, 0x63, 0x68,
	0x61, 0x72, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x30, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x69, 0x64, 0x22,
	0xbd, 0x01, 0x0a, 0x18, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x47, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x74, 0x66, 0x12, 0x39, 0x0a, 0x03,
	0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x19, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x55,
	0x53, 0x45, 0x52, 0x5f, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43,
	0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x44, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x54, 0x75, 0x74,
	0x6f, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x1d, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x50, 0x41,
	0x52, 0x41, 0x4d, 0x5f, 0x47, 0x52, 0x4f, 0x57, 0x5f, 0x52, 0x45, 0x57, 0x41, 0x52, 0x44, 0x5f,
	0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x20, 0x0a,
	0x0b, 0x67, 0x72, 0x6f, 0x77, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x0b, 0x67, 0x72, 0x6f, 0x77, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x22,
	0x95, 0x01, 0x0a, 0x15, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x77,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x43, 0x6d, 0x64, 0x12, 0x39, 0x0a, 0x03, 0x63, 0x6d, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x19, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52,
	0x5f, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52,
	0x03, 0x63, 0x6d, 0x64, 0x12, 0x41, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x6d, 0x64, 0x2e, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x3a, 0x1a, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x50, 0x41, 0x52, 0x41, 0x4d,
	0x5f, 0x47, 0x45, 0x54, 0x5f, 0x47, 0x52, 0x4f, 0x57, 0x5f, 0x52, 0x45, 0x57, 0x41, 0x52, 0x44,
	0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x3c, 0x0a, 0x0c, 0x54, 0x75, 0x74, 0x6f, 0x72,
	0x42, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xbe, 0x01, 0x0a, 0x15, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x54,
	0x61, 0x73, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x78, 0x43, 0x6d, 0x64, 0x12,
	0x39, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43,
	0x6d, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x3a, 0x19, 0x53, 0x43, 0x45, 0x4e,
	0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x5f, 0x50, 0x52, 0x4f,
	0x54, 0x4f, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x41, 0x0a, 0x05, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x6d, 0x64, 0x2e,
	0x54, 0x75, 0x74, 0x6f, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x3a, 0x1a, 0x54, 0x55, 0x54, 0x4f,
	0x52, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x55, 0x50, 0x44, 0x41,
	0x54, 0x45, 0x5f, 0x42, 0x4f, 0x58, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x27, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x43,
	0x6d, 0x64, 0x2e, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x42, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x2a, 0xce, 0x01, 0x0a, 0x0a, 0x54, 0x75, 0x74, 0x6f, 0x72,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1e, 0x0a, 0x1a, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x50, 0x41,
	0x52, 0x41, 0x4d, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f,
	0x4e, 0x54, 0x46, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x50, 0x41,
	0x52, 0x41, 0x4d, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x10, 0x02,
	0x12, 0x22, 0x0a, 0x1e, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x54,
	0x41, 0x53, 0x4b, 0x5f, 0x54, 0x45, 0x41, 0x43, 0x48, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x57, 0x41,
	0x52, 0x44, 0x10, 0x03, 0x12, 0x21, 0x0a, 0x1d, 0x54, 0x55, 0x54, 0x4f, 0x52, 0x50, 0x41, 0x52,
	0x41, 0x4d, 0x5f, 0x47, 0x52, 0x4f, 0x57, 0x5f, 0x52, 0x45, 0x57, 0x41, 0x52, 0x44, 0x5f, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x04, 0x12, 0x1e, 0x0a, 0x1a, 0x54, 0x55, 0x54, 0x4f, 0x52,
	0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x47, 0x52, 0x4f, 0x57, 0x5f, 0x52,
	0x45, 0x57, 0x41, 0x52, 0x44, 0x10, 0x05, 0x12, 0x1e, 0x0a, 0x1a, 0x54, 0x55, 0x54, 0x4f, 0x52,
	0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x5f, 0x42, 0x4f, 0x58, 0x10, 0x06,
}

var (
	file_Tutor_proto_rawDescOnce sync.Once
	file_Tutor_proto_rawDescData = file_Tutor_proto_rawDesc
)

func file_Tutor_proto_rawDescGZIP() []byte {
	file_Tutor_proto_rawDescOnce.Do(func() {
		file_Tutor_proto_rawDescData = protoimpl.X.CompressGZIP(file_Tutor_proto_rawDescData)
	})
	return file_Tutor_proto_rawDescData
}

var file_Tutor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Tutor_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_Tutor_proto_goTypes = []interface{}{
	(TutorParam)(0),                   // 0: Cmd.TutorParam
	(*TutorTaskItem)(nil),             // 1: Cmd.TutorTaskItem
	(*TutorRewardItem)(nil),           // 2: Cmd.TutorRewardItem
	(*TutorReward)(nil),               // 3: Cmd.TutorReward
	(*OfflineTutorReward)(nil),        // 4: Cmd.OfflineTutorReward
	(*TutorTaskUpdateNtf)(nil),        // 5: Cmd.TutorTaskUpdateNtf
	(*TutorTaskQueryCmd)(nil),         // 6: Cmd.TutorTaskQueryCmd
	(*TutorTaskTeacherRewardCmd)(nil), // 7: Cmd.TutorTaskTeacherRewardCmd
	(*TutorGrowRewardUpdateNtf)(nil),  // 8: Cmd.TutorGrowRewardUpdateNtf
	(*TutorGetGrowRewardCmd)(nil),     // 9: Cmd.TutorGetGrowRewardCmd
	(*TutorBoxItem)(nil),              // 10: Cmd.TutorBoxItem
	(*TutorTaskUpdateBoxCmd)(nil),     // 11: Cmd.TutorTaskUpdateBoxCmd
	(Command)(0),                      // 12: Cmd.Command
}
var file_Tutor_proto_depIdxs = []int32{
	2,  // 0: Cmd.TutorReward.item:type_name -> Cmd.TutorRewardItem
	3,  // 1: Cmd.OfflineTutorReward.teacherrewards:type_name -> Cmd.TutorReward
	12, // 2: Cmd.TutorTaskUpdateNtf.cmd:type_name -> Cmd.Command
	0,  // 3: Cmd.TutorTaskUpdateNtf.param:type_name -> Cmd.TutorParam
	1,  // 4: Cmd.TutorTaskUpdateNtf.items:type_name -> Cmd.TutorTaskItem
	12, // 5: Cmd.TutorTaskQueryCmd.cmd:type_name -> Cmd.Command
	0,  // 6: Cmd.TutorTaskQueryCmd.param:type_name -> Cmd.TutorParam
	1,  // 7: Cmd.TutorTaskQueryCmd.items:type_name -> Cmd.TutorTaskItem
	12, // 8: Cmd.TutorTaskTeacherRewardCmd.cmd:type_name -> Cmd.Command
	0,  // 9: Cmd.TutorTaskTeacherRewardCmd.param:type_name -> Cmd.TutorParam
	12, // 10: Cmd.TutorGrowRewardUpdateNtf.cmd:type_name -> Cmd.Command
	0,  // 11: Cmd.TutorGrowRewardUpdateNtf.param:type_name -> Cmd.TutorParam
	12, // 12: Cmd.TutorGetGrowRewardCmd.cmd:type_name -> Cmd.Command
	0,  // 13: Cmd.TutorGetGrowRewardCmd.param:type_name -> Cmd.TutorParam
	12, // 14: Cmd.TutorTaskUpdateBoxCmd.cmd:type_name -> Cmd.Command
	0,  // 15: Cmd.TutorTaskUpdateBoxCmd.param:type_name -> Cmd.TutorParam
	10, // 16: Cmd.TutorTaskUpdateBoxCmd.items:type_name -> Cmd.TutorBoxItem
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_Tutor_proto_init() }
func file_Tutor_proto_init() {
	if File_Tutor_proto != nil {
		return
	}
	file_xCmd_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Tutor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorTaskItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Tutor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorRewardItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Tutor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Tutor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineTutorReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Tutor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorTaskUpdateNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Tutor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorTaskQueryCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Tutor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorTaskTeacherRewardCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Tutor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorGrowRewardUpdateNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Tutor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorGetGrowRewardCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Tutor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorBoxItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Tutor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorTaskUpdateBoxCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Tutor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Tutor_proto_goTypes,
		DependencyIndexes: file_Tutor_proto_depIdxs,
		EnumInfos:         file_Tutor_proto_enumTypes,
		MessageInfos:      file_Tutor_proto_msgTypes,
	}.Build()
	File_Tutor_proto = out.File
	file_Tutor_proto_rawDesc = nil
	file_Tutor_proto_goTypes = nil
	file_Tutor_proto_depIdxs = nil
}
